import { expect, test as demoTest, selectDemoIdentity, waitForPortal } from './fixtures.js'
import { test as apiTest, passwordSignIn, verifyAuthenticator } from './auth-api-fixture.js'
import { directoryData } from '../src/test/directory.js'

async function openCreate(page) {
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  const menu = page.getByRole('menu', { name: 'Profile menu' })
  await expect(menu.getByRole('menuitem').first()).toHaveText('Create Admin')
  await menu.getByRole('menuitem', { name: 'Create Admin', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Create Admin' })).toBeVisible()
}
async function details(page) {
  await page.getByLabel('Staff name', { exact: true }).fill('Operations Staff')
  await page.getByLabel('Staff email', { exact: true }).fill('admin@example.test')
  await page.getByLabel('Staff phone number', { exact: true }).fill('91234567')
  await page.getByLabel('Staff birthday', { exact: true }).fill('1990-01-02')
  await page.getByLabel('Staff gender', { exact: true }).selectOption('Female')
}
async function apiSignIn(page, staffApi) {
  staffApi.state.step = 'SOFTWARE_TOKEN_MFA'
  await page.goto(staffApi.origin)
  await passwordSignIn(page)
  await verifyAuthenticator(page)
}

demoTest('Owner creates Admin through the first profile option and the Admin cannot open rates or remuneration', async ({ page }) => {
  await page.goto('/')
  await waitForPortal(page)
  await openCreate(page)
  await expect(page.getByLabel('Staff phone country code')).toHaveValue('+65')
  await expect(page.getByLabel('Trainer type', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveCount(0)
  await details(page)
  await page.getByRole('button', { name: 'Create Admin', exact: true }).click()
  await expect(page.getByText('This is a demo account. No email was sent.')).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Create Admin' })).toHaveCount(0)
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('fitfinity-m2-demo-db-v4')).users.find(row => row.email === 'admin@example.test').id)
  await selectDemoIdentity(page, id)
  await page.goto('/#/trainers/t1')
  await expect(page.getByRole('heading', { name: 'Marcus Tan', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Training & Rates' })).toHaveCount(0)
  await expect(page.getByText('$80 / session', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  await expect(page.getByRole('menuitem', { name: 'Create Admin' })).toHaveCount(0)
  await page.goto('/#/remuneration')
  await expect(page.getByText('Remuneration is unavailable for this account.')).toBeVisible()
  await page.goto('/#/trainers/new')
  await expect(page.getByRole('heading', { name: 'Add New Trainer' })).toBeVisible()
  await page.getByLabel('Trainer name', { exact: true }).fill('Admin Created Coach')
  await page.getByLabel('Trainer email', { exact: true }).fill('admin-coach@example.test')
  await page.getByLabel('Trainer phone number', { exact: true }).fill('91234567')
  await page.getByLabel('Trainer birthday', { exact: true }).fill('1990-01-02')
  await page.getByLabel('Trainer gender', { exact: true }).selectOption('Female')
  await page.getByLabel('Trainer type', { exact: true }).fill('Personal')
  await expect(page.getByLabel('Creation progress')).toHaveText('Step 1 of 4')
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Continue to Trainer Availability' }).click()
  await page.getByRole('button', { name: 'Sunday', exact: true }).click()
  await page.getByRole('button', { name: 'Add Time', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to Owner Approval Needed' }).click()
  await page.getByRole('button', { name: 'Continue to Review & Confirm' }).click()
  await expect(page.getByRole('heading', { name: 'Review & Confirm', exact: true })).toBeVisible()
  await expect(page.getByText('Training & Rates', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Create Trainer', exact: true }).click()
  await page.getByRole('dialog', { name: 'Create Admin Created Coach?' }).getByRole('button', { name: 'Create Trainer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Admin Created Coach', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Training & Rates' })).toHaveCount(0)
  const saved = await page.evaluate(() => {
    const db = JSON.parse(localStorage.getItem('fitfinity-m2-demo-db-v4'))
    return { rates: db.trainers.find(row => row.email === 'admin-coach@example.test').rates, defaults: db.settings.trainerRates }
  })
  expect(saved.rates).toEqual(saved.defaults)
})

demoTest('Admin popup validates required fields and dirty browser Back preserves the draft when cancelled', async ({ page }) => {
  await page.goto('/')
  await waitForPortal(page)
  await openCreate(page)
  await page.getByRole('button', { name: 'Create Admin', exact: true }).click()
  await expect(page.getByLabel('Staff name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Staff name', { exact: true }).fill('Unsaved staff')
  await page.goBack()
  const guard = page.getByRole('dialog', { name: 'Leave this edit?' })
  await expect(guard).toBeVisible()
  await guard.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Staff name', { exact: true })).toHaveValue('Unsaved staff')
  const dialog = page.getByRole('dialog', { name: 'Create Admin' })
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await guard.getByRole('button', { name: 'Leave Without Saving', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Owner Dashboard' })).toBeVisible()
})

demoTest('Trainer cannot reach Admin creation by a direct URL', async ({ page }) => {
  await page.goto('/')
  await waitForPortal(page)
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('fitfinity-m2-demo-db-v4')).users.find(row => row.role === 'trainer').id)
  await selectDemoIdentity(page, id)
  await page.goto('/#/owner-profile/create-admin')
  await expect(page.getByText('This profile is available to the owner.')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Create Admin' })).toHaveCount(0)
})

demoTest('A created demo Admin can open My Profile, reload it and go Back to the previous page', async ({ page }) => {
  await page.goto('/')
  await waitForPortal(page)
  await openCreate(page)
  await details(page)
  await page.getByRole('button', { name: 'Create Admin', exact: true }).click()
  await expect(page.getByText('This is a demo account. No email was sent.')).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('fitfinity-m2-demo-db-v4')).users.find(row => row.email === 'admin@example.test').id)
  await selectDemoIdentity(page, id)
  await page.goto('/#/trainers/t1')
  await expect(page.getByRole('heading', { name: 'Marcus Tan', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  await expect(page.getByRole('menuitem', { name: 'Create Admin' })).toHaveCount(0)
  await page.getByRole('menuitem', { name: 'My Profile', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Operations Staff', exact: true })).toBeVisible()
  await expect(page.getByText('admin@example.test', { exact: true })).toBeVisible()
  await expect(page.getByText(/Changes and other workflows will be available/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Remuneration', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Operations Staff', exact: true })).toBeVisible()
  await expect(page.locator('.profile-info-grid .info-row strong').filter({ hasText: /^Admin$/ })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Marcus Tan', exact: true })).toBeVisible()
})

demoTest('HTTP-preview capabilities allow Admin creation without randomUUID or a stuck submit button', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(globalThis.crypto, 'randomUUID', { configurable: true, value: undefined })
  })
  await page.goto('/')
  await waitForPortal(page)
  expect(await page.evaluate(() => typeof crypto.randomUUID)).toBe('undefined')
  expect(await page.evaluate(() => typeof crypto.getRandomValues)).toBe('function')
  await openCreate(page)
  await details(page)
  await page.getByRole('button', { name: 'Create Admin', exact: true }).click()
  await expect(page.getByText('This is a demo account. No email was sent.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Creating…', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.reload()
  await waitForPortal(page)
  const rows = await page.evaluate(() => JSON.parse(localStorage.getItem('fitfinity-m2-demo-db-v4')).users.filter(row => row.email === 'admin@example.test'))
  expect(rows).toHaveLength(1)
  expect(rows[0]).toMatchObject({ role: 'admin', status: 'active' })
  expect(rows[0].id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)
})

apiTest('Live-mode Owner creation uses the authenticated API and preserves the same account after reload', async ({ page, staffApi }) => {
  await apiSignIn(page, staffApi)
  await openCreate(page)
  await details(page)
  await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
  await expect(page.getByText(/invitation email was requested for admin@example.test/)).toBeVisible()
  const writes = staffApi.state.mutations.filter(row => row.path === '/api/staff/admins')
  expect(writes).toHaveLength(1)
  expect(writes[0].idempotencyKey).toMatch(/^[0-9a-f-]{36}$/)
  expect(writes[0].keys.sort()).toEqual(['birthday', 'email', 'gender', 'name', 'phone_country_code', 'phone_number'])
  expect(staffApi.state.adminAccounts.size).toBe(1)
  const saved = await page.evaluate(() => JSON.stringify({ local: localStorage, session: sessionStorage }))
  expect(saved).not.toContain('admin@example.test')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.reload()
  expect(staffApi.state.adminAccounts.size).toBe(1)
})

apiTest('An interrupted invitation keeps the form fixed and retries the same request without another account', async ({ page, staffApi }) => {
  staffApi.state.adminCreateFailure = true
  await apiSignIn(page, staffApi)
  await openCreate(page)
  await details(page)
  await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Staff service unavailable' })).toBeVisible()
  await expect(page.getByLabel('Staff email', { exact: true })).toBeDisabled()
  // The native history guard must survive the directory view being removed.
  staffApi.state.unavailable = true
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByRole('heading', { name: 'Unable to load the portal' })).toBeVisible()
  await page.goBack()
  const leave = page.getByRole('dialog', { name: 'Leave this edit?' })
  await expect(leave).toBeVisible()
  await leave.getByRole('button', { name: 'Cancel', exact: true }).click()
  staffApi.state.unavailable = false
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByLabel('Staff email', { exact: true })).toHaveValue('admin@example.test')
  await expect(page.getByLabel('Staff email', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Check Account Setup' }).click()
  await expect(page.getByText(/Invitation delivery is not confirmed/)).toBeVisible()
  const writes = staffApi.state.mutations.filter(row => row.path === '/api/staff/admins')
  expect(writes).toHaveLength(2)
  expect(writes[1].idempotencyKey).toBe(writes[0].idempotencyKey)
  expect(writes[1].body).toEqual(writes[0].body)
  expect(staffApi.state.adminAccounts.size).toBe(1)
})

apiTest('Live Admin opens trainer and package directories with rates absent and creation unavailable', async ({ page, staffApi }) => {
  staffApi.state.user = { ...staffApi.state.user, name: 'Operations Admin', role: 'admin' }
  const data = directoryData()
  delete data.trainers[0].peak_rate_cents; delete data.trainers[0].off_peak_rate_cents
  staffApi.state.directory = data
  await apiSignIn(page, staffApi)
  await page.getByRole('button', { name: 'View Trainers', exact: true }).click()
  await page.getByRole('button', { name: 'View API Trainer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Training & Rates' })).toHaveCount(0)
  await expect(page.getByText('$80 / session', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  await expect(page.getByRole('menuitem', { name: 'Create Admin' })).toHaveCount(0)
  await page.getByRole('menuitem', { name: 'My Profile', exact: true }).click()
  await page.getByRole('button', { name: 'Home', exact: true }).click()
  await page.getByRole('button', { name: 'View Packages', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View package Current Template', exact: true })).toBeVisible()
})

apiTest('A delayed old-session expiry preserves a newer Owner login and its new Admin draft', async ({ page, staffApi }) => {
  await apiSignIn(page, staffApi)
  const oldToken = staffApi.state.csrfToken
  const held = staffApi.holdNextAdminExpiry()
  try {
    await apiTest.step('Hold the old-session Admin POST at the HTTP server', async () => {
      await openCreate(page); await details(page)
      await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
      await expect.poll(() => held.request?.csrf).toBe(oldToken)
      expect(staffApi.state.adminAccounts.size).toBe(0)
    })
    await apiTest.step('Verify the replacement Owner session and enter its new draft', async () => {
      staffApi.state.csrfToken = 'b'.repeat(64)
      await page.evaluate(() => window.dispatchEvent(new Event('focus')))
      await expect(page.getByLabel('Staff name', { exact: true })).toHaveValue('')
      await details(page)
      await page.getByLabel('Staff name', { exact: true }).fill('New Session Staff')
    })
    await apiTest.step('Deliver the old expiry and retain the new draft', async () => {
      const expired = page.waitForResponse(response => response.url().endsWith('/api/staff/admins') && response.status() === 401)
      held.release()
      const response = await expired
      expect(await response.json()).toMatchObject({ error: { code: 'SESSION_EXPIRED' } })
      expect(response.headers()['set-cookie']).toBeUndefined()
      await expect.poll(() => held.sent).toBe(true)
      await expect(page.getByLabel('Staff name', { exact: true })).toHaveValue('New Session Staff')
    })
    await apiTest.step('Create exactly one Admin under the new session', async () => {
      await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
      await expect(page.getByText(/invitation email was requested for admin@example.test/)).toBeVisible()
      // Both requests now cross HTTP: the expired old request and the successful new one.
      const writes = staffApi.state.mutations.filter(row => row.path === '/api/staff/admins')
      expect(writes).toHaveLength(2)
      expect(writes[0]).toMatchObject({ csrf: oldToken, body: { name: 'Operations Staff' } })
      expect(writes[1]).toMatchObject({ csrf: staffApi.state.csrfToken, body: { name: 'New Session Staff' } })
      expect(writes[1].idempotencyKey).not.toBe(writes[0].idempotencyKey)
      expect(staffApi.state.adminAccounts.size).toBe(1)
    })
  } finally { held.release() }
})


apiTest('An Admin draft cannot cross a replacement session discovered at submit', async ({ page, staffApi }) => {
  await apiSignIn(page, staffApi)
  await openCreate(page); await details(page)
  await apiTest.step('Discover the replacement at preflight without submitting the old draft', async () => {
    staffApi.state.csrfToken = 'b'.repeat(64)
    await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
    await expect(page.getByLabel('Staff name', { exact: true })).toHaveValue('')
    expect(staffApi.state.mutations.filter(row => row.path === '/api/staff/admins')).toHaveLength(0)
    expect(staffApi.state.adminAccounts.size).toBe(0)
  })
  await apiTest.step('Submit once after entering the new session draft', async () => {
    await details(page)
    await page.getByLabel('Staff name', { exact: true }).fill('Replacement Session Staff')
    await page.getByRole('button', { name: 'Create Admin & Send Invitation' }).click()
    await expect(page.getByText(/invitation email was requested for admin@example.test/)).toBeVisible()
    const writes = staffApi.state.mutations.filter(row => row.path === '/api/staff/admins')
    expect(writes).toHaveLength(1)
    expect(writes[0]).toMatchObject({ csrf: staffApi.state.csrfToken, body: { name: 'Replacement Session Staff' } })
    expect(staffApi.state.adminAccounts.size).toBe(1)
  })
})
