import { mockPhysicalOrientation, expectRequiredFieldHighlights, fillClientRequiredFields, waitForPortal, expect, test, selectDemoIdentity } from './fixtures.js'

const DB_KEY = 'fitfinity-m2-demo-db-v4'
const stepHeading = (page, name) => page.getByRole('heading', { level: 2, name, exact: true })
const continueTo = async (page, name) => {
  await page.getByRole('button', { name: `Continue to ${name}`, exact: true }).click()
  const actions = page.locator('.onboarding-step-actions')
  const backButton = actions.getByRole('button', { name: /^Back to / })
  if (await backButton.count()) {
    const back = await backButton.boundingBox()
    const next = await actions.locator('button[type="submit"]').boundingBox()
    expect(back.x + back.width).toBeLessThanOrEqual(next.x)
    expect(Math.abs(back.y + back.height - next.y - next.height)).toBeLessThanOrEqual(2)
  }
}
const backTo = (page, name) => page.getByRole('button', { name: `Back to ${name}`, exact: true }).click()

async function beginClient(page, name = 'M3 Created Client', frequency = '1', remarks = '') {
  await page.goto('/#/clients/new')
  await page.getByLabel('Client name', { exact: true }).fill(name)
  await fillClientRequiredFields(page)
  await page.getByLabel('Remarks', { exact: true }).fill(remarks)
  await continueTo(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await page.getByLabel('Weekly frequency', { exact: true }).selectOption(frequency)
}

async function addPreference(page, days = ['Monday']) {
  for (const day of days) await page.getByRole('button', { name: day, exact: true }).click()
  await page.getByLabel('Availability from', { exact: true }).fill('18:00')
  await page.getByLabel('Availability to', { exact: true }).fill('19:00')
  await page.getByRole('button', { name: 'Add Time', exact: true }).click()
}

async function finishMatching(page, days = ['Monday']) {
  await continueTo(page, 'Client Availability')
  await addPreference(page, days)
  await continueTo(page, 'Trainer Matching')
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeVisible()
}

async function reviewClient(page) {
  if (!(await stepHeading(page, 'Review & Confirm').isVisible())) await continueTo(page, 'Review & Confirm')
  await expect(stepHeading(page, 'Review & Confirm')).toBeVisible()
}

async function createClient(page, name) {
  await reviewClient(page)
  await page.getByRole('button', { name: 'Create Client', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: `Create ${name}?`, exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Create Client', exact: true }).click()
  await expect(page.getByRole('heading', { name, level: 1, exact: true })).toBeVisible()
}

async function savedClient(page, name) {
  return page.evaluate(({ key, name }) => {
    const db = JSON.parse(localStorage.getItem(key))
    const client = db.clients.find(item => item.name === name)
    return {
      client,
      count: db.clients.filter(item => item.name === name).length,
      sessions: db.sessions.filter(item => item.clientId === client.id),
      messages: db.messages.filter(item => item.clientId === client.id),
    }
  }, { key: DB_KEY, name })
}

async function noHorizontalOverflow(page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(0)
}

test('M3 Add Client shows only the current section, labels required fields and validates Continue', async ({ page }) => {
  await page.goto('/#/clients/new')
  await waitForPortal(page)
  const before = await page.evaluate(key => localStorage.getItem(key), DB_KEY)
  await expect(stepHeading(page, 'General Information')).toBeVisible()
  await expect(page.locator('.client-onboarding .panel')).toHaveCount(1)
  await expect(page.getByLabel('Start date', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Matched trainer', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Create Client', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Client name', { exact: true })).toHaveAttribute('aria-required', 'true')
  await expect(page.getByLabel('Client birthday', { exact: true })).toHaveAttribute('aria-required', 'true')
  await expectRequiredFieldHighlights(page, 11)
  for (const label of ['Client health or limitation notes', 'Remarks']) {
    await expect(page.getByLabel(label, { exact: true })).not.toHaveAttribute('required')
    await expect(page.getByLabel(label, { exact: true })).toHaveCSS('border-top-color', 'rgb(58, 63, 75)')
  }

  await continueTo(page, 'Package & Preferences')
  await expect(stepHeading(page, 'General Information')).toBeVisible()
  await expect(page.getByLabel('Client name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await expectRequiredFieldHighlights(page, 11)
  await page.getByLabel('Client name', { exact: true }).fill('Sequential Client')
  await fillClientRequiredFields(page)
  await continueTo(page, 'Package & Preferences')
  await expect(page.getByLabel('Client name', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Start date', { exact: true })).toHaveAttribute('aria-required', 'true')
  await continueTo(page, 'Client Availability')
  await expect(stepHeading(page, 'Package & Preferences')).toBeVisible()
  await expect(page.getByLabel('Start date', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await continueTo(page, 'Client Availability')
  await expect(stepHeading(page, 'Package & Preferences')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await continueTo(page, 'Trainer Matching')
  await expect(stepHeading(page, 'Client Availability')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Add at least one availability block.')
  expect(await page.evaluate(key => localStorage.getItem(key), DB_KEY)).toBe(before)
  await noHorizontalOverflow(page)
})

test('M3 Add Client reset clears only availability and matching, then rematching works again', async ({ page }) => {
  await beginClient(page, 'Reset Test Client', '2', 'Keep this shared remark')
  await page.getByLabel('Trainer preference', { exact: true }).selectOption('Female trainer preferred')
  await finishMatching(page, ['Monday', 'Wednesday'])
  await backTo(page, 'Client Availability')
  await page.getByRole('button', { name: 'Reset Availability', exact: true }).click()
  await expect(page.getByText('No availability blocks added yet.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Availability from', { exact: true })).toHaveValue('18:00')
  await expect(page.getByLabel('Availability to', { exact: true })).toHaveValue('19:00')
  await backTo(page, 'Package & Preferences')
  await expect(page.getByLabel('Start date', { exact: true })).toHaveValue('2026-09-07')
  await expect(page.getByLabel('Weekly frequency', { exact: true })).toHaveValue('2')
  await expect(page.getByLabel('Trainer preference', { exact: true })).toHaveValue('Female trainer preferred')
  await expect(page.getByLabel('Remarks', { exact: true })).toHaveCount(0)
  await backTo(page, 'General Information')
  await expect(page.getByLabel('Remarks', { exact: true })).toHaveValue('Keep this shared remark')
  await expect(page.getByLabel('Client name', { exact: true })).toHaveValue('Reset Test Client')
  await continueTo(page, 'Package & Preferences')
  await continueTo(page, 'Client Availability')
  await addPreference(page, ['Monday', 'Wednesday'])
  await continueTo(page, 'Trainer Matching')
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeVisible()
  await noHorizontalOverflow(page)
})

test('M3 owner creates a once-weekly 12-session / 90-day client through the service boundary', async ({ page }) => {
  const runtimeErrors = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  await beginClient(page)
  await finishMatching(page)
  await createClient(page, 'M3 Created Client')
  await expect(page.locator('.info-row').filter({ has: page.getByText('Birthday', { exact: true }) }).locator('strong')).toHaveText('02 Jan 1990')
  expect(runtimeErrors).toEqual([])
  const saved = await savedClient(page, 'M3 Created Client')
  expect(saved.count).toBe(1)
  expect(saved.client.package).toMatchObject({ durationWeeks: 12, sessionsPerWeek: 1, total: 12, used: 0, validityDays: 90, startDate: '2026-09-07', endDate: '2026-12-05' })
  expect(saved.sessions).toHaveLength(12)
  expect(saved.sessions.at(-1).sessionNumber).toBe(12)
  expect(saved.messages.find(item => item.kind === 'client_assignment').read).toBe(false)
  expect(saved.messages.find(item => item.kind === 'client_created').read).toBe(false)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'M3 Created Client', level: 1 })).toBeVisible()
})

test('M3 Add Client keeps Client name clear of Client type and uses compact action buttons', async ({ page, isMobile }) => {
  if (isMobile) await mockPhysicalOrientation(page)
  await page.goto('/#/clients/new')
  const type = await page.getByLabel('Client type', { exact: true }).boundingBox()
  const label = await page.getByText('Client name', { exact: true }).boundingBox()
  const input = await page.getByLabel('Client name', { exact: true }).boundingBox()
  expect(type).not.toBeNull(); expect(label).not.toBeNull(); expect(input).not.toBeNull()
  expect(label.y).toBeGreaterThanOrEqual(type.y + type.height + 12)
  expect(input.y).toBeGreaterThan(label.y + label.height)
  await noHorizontalOverflow(page)
  await page.getByLabel('Client name', { exact: true }).fill('Size Test')
  await fillClientRequiredFields(page)
  await page.getByLabel('Client gender', { exact: true }).click()
  const choices = page.getByRole('listbox', { name: 'Client gender', exact: true })
  await expect(choices).toBeVisible()
  const menuBox = await choices.boundingBox()
  expect(menuBox.height).toBeLessThan(page.viewportSize().height * .65)
  expect(menuBox.x).toBeGreaterThanOrEqual(0)
  expect(menuBox.x + menuBox.width).toBeLessThanOrEqual(page.viewportSize().width)
  await choices.getByRole('option', { name: 'Female', exact: true }).click()
  await expect(choices).toHaveCount(0)
  const birthday = page.getByLabel('Client birthday', { exact: true })
  await expect(birthday).toHaveAttribute('type', 'text')
  await birthday.click()
  const calendar = page.getByRole('dialog', { name: 'Client birthday calendar', exact: true })
  await expect(calendar).toBeVisible()
  const calendarBox = await calendar.boundingBox()
  expect(calendarBox.width).toBeLessThanOrEqual(310)
  expect(calendarBox.x).toBeGreaterThanOrEqual(0)
  expect(calendarBox.x + calendarBox.width).toBeLessThanOrEqual(page.viewportSize().width)
  await calendar.getByLabel('Calendar picker month', { exact: true }).click()
  await calendar.getByRole('listbox', { name: 'Calendar picker month' }).getByRole('option', { name: 'February', exact: true }).click()
  await calendar.getByRole('button', { name: '03 Feb 1990', exact: true }).click()
  await expect(birthday).toHaveValue('1990-02-03')
  await expect(calendar).toHaveCount(0)
  if (isMobile) {
    await page.evaluate(() => { screen.orientation.type = 'landscape-primary'; screen.orientation.dispatchEvent(new Event('change')) })
    await expect(page.getByRole('dialog', { name: 'Please rotate your device' })).toBeVisible()
    await expect(page.locator('#root')).toHaveAttribute('inert', '')
    await page.evaluate(() => { screen.orientation.type = 'portrait-primary'; screen.orientation.dispatchEvent(new Event('change')) })
    await expect(page.getByRole('dialog', { name: 'Please rotate your device' })).toHaveCount(0)
    await expect(page.getByLabel('Client name', { exact: true })).toHaveValue('Size Test')
    await expect(birthday).toHaveValue('1990-02-03')
  }
  await continueTo(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await continueTo(page, 'Client Availability')
  for (const name of ['Add Time', 'Reset Availability']) {
    const button = page.getByRole('button', { name, exact: true })
    const box = await button.boundingBox()
    expect(box.height).toBeLessThanOrEqual(40)
    expect(box.width).toBeLessThanOrEqual(name === 'Add Time' ? 100 : 150)
    await expect(button).toHaveCSS('font-size', '11px')
  }
  await noHorizontalOverflow(page)
})

test('M3 current section scrolls without CSS overrides on desktop and mobile WebKit', async ({ page, browserName, isMobile }) => {
  if (isMobile) await mockPhysicalOrientation(page)
  const originalViewport = page.viewportSize()
  await page.setViewportSize({ width: originalViewport.width, height: 480 })
  await page.goto('/#/clients/new')
  const continueButton = page.getByRole('button', { name: 'Continue to Package & Preferences', exact: true })
  // Navigation can finish before React renders the form. Wait for the actual
  // section and its layout before measuring overflow in the short viewport.
  await expect(continueButton).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.scrollingElement.scrollHeight - innerHeight)).toBeGreaterThan(0)
  await expect(page.locator('body')).not.toHaveCSS('position', 'fixed')

  if (browserName === 'chromium') {
    // Exercise native touch scrolling in Chrome's narrow phone emulation too;
    // programmatic scrollTo and mouse-wheel input bypass touch cancellation.
    const input = await page.context().newCDPSession(page)
    try {
      await page.setViewportSize({ width: 390, height: 480 })
      await input.send('Emulation.setTouchEmulationEnabled', { enabled: true, maxTouchPoints: 1 })
      await page.evaluate(() => scrollTo(0, 0))
      await input.send('Input.synthesizeScrollGesture', { x: 368, y: 360, yDistance: -240, gestureSourceType: 'touch' })
      await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
      const lowerPosition = await page.evaluate(() => window.scrollY)
      await input.send('Input.synthesizeScrollGesture', { x: 368, y: 140, yDistance: 160, gestureSourceType: 'touch' })
      await expect.poll(() => page.evaluate(() => window.scrollY)).toBeLessThan(lowerPosition)
    } finally {
      await input.send('Emulation.setTouchEmulationEnabled', { enabled: false })
      await input.detach()
      await page.setViewportSize({ width: originalViewport.width, height: 480 })
      await page.evaluate(() => scrollTo(0, 0))
    }
  }

  if (browserName === 'webkit' && isMobile) {
    // Mobile WebKit has no mouse-wheel command. Exercise document scrolling
    // without modifying styles; physical finger-swipe feel remains manual QA.
    await page.evaluate(() => window.scrollTo(0, document.scrollingElement.scrollHeight))
  } else {
    await page.mouse.move(originalViewport.width - 22, 250)
    await page.mouse.wheel(0, 10000)
  }
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  await expect(continueButton).toBeInViewport()
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await expect(page.getByLabel('Client type', { exact: true })).toBeInViewport()
  await noHorizontalOverflow(page)
})

test('M3 Couple requires both names and creates one account with two people and 24 sessions', async ({ page }) => {
  await page.goto('/#/clients/new')
  await page.getByLabel('Client type', { exact: true }).selectOption('Couple')
  await page.getByLabel('Client 1 name', { exact: true }).fill('Alpha Test')
  await expectRequiredFieldHighlights(page, 11)
  await fillClientRequiredFields(page, 'Client 1')
  await page.getByLabel('Client 1 health or limitation notes', { exact: true }).fill('Alpha health notes')
  await continueTo(page, 'Package & Preferences')
  await expect(stepHeading(page, 'General Information')).toBeVisible()
  await expect(page.getByLabel('Client 2 name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Client 2 name', { exact: true }).fill('Beta Test')
  await expectRequiredFieldHighlights(page, 11)
  await fillClientRequiredFields(page, 'Client 2')
  await page.getByLabel('Client 2 health or limitation notes', { exact: true }).fill('Beta health notes')
  await page.getByLabel('Remarks', { exact: true }).fill('Shared couple remark')
  await page.getByRole('button', { name: 'Client 1', exact: true }).click()
  await expect(page.getByLabel('Client 1 name', { exact: true })).toHaveValue('Alpha Test')
  await continueTo(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await page.getByLabel('PT Package', { exact: true }).selectOption('package-24')
  await page.getByLabel('Weekly frequency', { exact: true }).selectOption('2')
  await finishMatching(page, ['Monday', 'Wednesday'])
  await createClient(page, 'Alpha Test & Beta Test')
  const saved = await savedClient(page, 'Alpha Test & Beta Test')
  expect(saved.count).toBe(1)
  expect(saved.client.people).toHaveLength(2)
  expect(saved.client.people.map(person => person.healthNotes)).toEqual(['Alpha health notes', 'Beta health notes'])
  expect(saved.client.remarks).toBe('Shared couple remark')
  expect(saved.client.package.total).toBe(24)
  expect(saved.sessions).toHaveLength(24)
  expect(saved.sessions.every(session => session.date <= saved.client.package.endDate)).toBe(true)
})

test('M3 editing earlier scheduling choices clears stale matches and revalidates the cadence', async ({ page }) => {
  await beginClient(page, 'Changed Match Client')
  await finishMatching(page)
  await backTo(page, 'Client Availability')
  await backTo(page, 'Package & Preferences')
  await page.getByLabel('PT Package', { exact: true }).selectOption('package-24')
  await page.getByLabel('Weekly frequency', { exact: true }).selectOption('2')
  await page.getByLabel('Trainer preference', { exact: true }).selectOption('Female trainer preferred')
  await continueTo(page, 'Client Availability')
  await continueTo(page, 'Trainer Matching')
  await expect(stepHeading(page, 'Client Availability')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('two possible days')
  await addPreference(page, ['Wednesday'])
  await continueTo(page, 'Trainer Matching')
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Matched trainer', { exact: true }).locator('option', { hasText: 'Marcus Tan' })).toHaveCount(0)
  await expect(page.getByLabel('Fixed Weekly Schedule', { exact: true }).locator('div')).toHaveCount(2)
})

test('M3 final confirmation can be cancelled without creating records and then retried', async ({ page }) => {
  await beginClient(page, 'Confirmation Client')
  await finishMatching(page)
  await reviewClient(page)
  const before = await page.evaluate(key => localStorage.getItem(key), DB_KEY)
  await page.getByRole('button', { name: 'Create Client', exact: true }).click()
  await page.getByRole('dialog', { name: 'Create Confirmation Client?', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(stepHeading(page, 'Review & Confirm')).toBeVisible()
  expect(await page.evaluate(key => localStorage.getItem(key), DB_KEY)).toBe(before)
  await createClient(page, 'Confirmation Client')
  expect((await savedClient(page, 'Confirmation Client')).count).toBe(1)
})

test('M3 cancel uses the existing unsaved-edit guard without losing the draft when staying', async ({ page }) => {
  await page.goto('/#/clients/new')
  await page.getByLabel('Client name', { exact: true }).fill('Keep My Draft')
  await fillClientRequiredFields(page)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Leave this edit?', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Client name', { exact: true })).toHaveValue('Keep My Draft')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await dialog.getByRole('button', { name: 'Leave Without Saving', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Clients', level: 1, exact: true })).toBeVisible()
})

test('M3 automatic matching shows the dropdown and a recoverable no-results state without another button', async ({ page }) => {
  await beginClient(page, 'No Match Client')
  await continueTo(page, 'Client Availability')
  await addPreference(page, ['Sunday'])
  await continueTo(page, 'Trainer Matching')
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('No active trainer matches')
  const before = await page.evaluate(key => localStorage.getItem(key), DB_KEY)
  await continueTo(page, 'Review & Confirm')
  await expect(stepHeading(page, 'Trainer Matching')).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(key => localStorage.getItem(key), DB_KEY)).toBe(before)
  await backTo(page, 'Client Availability')
  await page.getByRole('button', { name: 'Reset Availability', exact: true }).click()
  await addPreference(page)
  await continueTo(page, 'Trainer Matching')
  await expect(page.getByLabel('Matched trainer', { exact: true })).toBeEnabled()
  await expect(page.getByLabel('Matched trainer', { exact: true })).not.toHaveValue('')
})

test('M3 owner dashboard Add Client quick action opens the canonical form and returns to the dashboard', async ({ page }) => {
  await page.goto('/#/dashboard')
  const action = page.getByRole('button', { name: 'Add Client', exact: true })
  await expect(action).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Calendar', exact: true })).toBeVisible()
  expect((await action.boundingBox()).height).toBeLessThanOrEqual(40)
  await noHorizontalOverflow(page)
  await action.click()
  await expect(page).toHaveURL(/#\/clients\/new$/)
  await expect(page.getByRole('heading', { name: 'Add New Client', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Owner Dashboard', exact: true })).toBeVisible()
})

test('M3 trainer has no owner dashboard quick action or trainer-creation route', async ({ page }) => {
  await page.goto('/#/dashboard')
  await selectDemoIdentity(page, 'u-marcus')
  await expect(page.getByRole('heading', { name: 'Trainer Dashboard', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add Client', exact: true })).toHaveCount(0)
  await page.evaluate(() => { location.hash = '#/trainers/new' })
  await expect(page.getByRole('heading', { name: 'Add New Trainer', exact: true })).toHaveCount(0)
  await expect(page.getByRole('form', { name: 'Trainer creation', exact: true })).toHaveCount(0)
})

const clientSummary = (page, title) => page.getByRole('region', { name: title, exact: true })
const returnToClientReview = page => page.getByRole('button', { name: 'Return to Review & Confirm', exact: true }).click()

test('M3 client summary displays all entered information and section-specific Edit links before saving', async ({ page }) => {
  await page.goto('/#/clients/new')
  await waitForPortal(page)
  const before = await page.evaluate(key => localStorage.getItem(key), DB_KEY)
  await page.getByLabel('Client name', { exact: true }).fill('Summary Client')
  await fillClientRequiredFields(page)
  await page.getByLabel('Client phone number', { exact: true }).fill('9123 4567')
  await page.getByLabel('Client email', { exact: true }).fill('summary@example.com')
  await page.getByLabel('Client birthday', { exact: true }).fill('1994-04-12')
  await page.getByLabel('Client gender', { exact: true }).selectOption('Female')
  await page.getByLabel('Client emergency contact name', { exact: true }).fill('Emergency Person')
  await page.getByLabel('Client emergency contact relationship', { exact: true }).selectOption('Sibling')
  await page.getByLabel('Client emergency contact country code', { exact: true }).selectOption('+60')
  await page.getByLabel('Client emergency contact phone number', { exact: true }).fill('123456789')
  await page.getByLabel('Client health or limitation notes', { exact: true }).fill('Health notes for review')
  await page.getByLabel('Remarks', { exact: true }).fill('Shared review remark')
  await continueTo(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await finishMatching(page)
  const trainerName = await page.getByLabel('Matched trainer', { exact: true }).locator('option:checked').innerText()
  await expect(page.getByRole('button', { name: 'Create Client', exact: true })).toHaveCount(0)
  await reviewClient(page)
  await expect(page.getByLabel('Creation progress', { exact: true })).toHaveText('Step 5 of 5')
  await expect(page.getByLabel('Form summary', { exact: true }).locator('input,select,textarea')).toHaveCount(0)
  for (const text of ['Summary Client', '+65 9123 4567', 'summary@example.com', '12 Apr 1994', 'Female', 'Emergency Person', 'Sibling', '+60 123456789', 'Health notes for review']) {
    await expect(clientSummary(page, 'General Information')).toContainText(text)
  }
  await expect(clientSummary(page, 'General Information')).toContainText('Shared review remark')
  await expect(clientSummary(page, 'Client Availability')).toContainText('Monday · 18:00–19:00')
  await expect(clientSummary(page, 'Trainer Matching')).toContainText(trainerName)
  for (const title of ['General Information', 'Package & Preferences', 'Client Availability', 'Trainer Matching']) {
    await expect(page.getByRole('button', { name: `Edit ${title}`, exact: true })).toBeVisible()
  }
  expect(await page.evaluate(key => localStorage.getItem(key), DB_KEY)).toBe(before)
  await noHorizontalOverflow(page)
})

test('M3 client summary quick edit validates the selected section and returns directly with all other values retained', async ({ page }) => {
  await beginClient(page, 'Before Quick Edit', '1', 'Keep account remark')
  await finishMatching(page)
  const trainerId = await page.getByLabel('Matched trainer', { exact: true }).inputValue()
  await reviewClient(page)
  const before = await page.evaluate(key => localStorage.getItem(key), DB_KEY)
  await page.getByRole('button', { name: 'Edit General Information', exact: true }).click()
  await expect(page.getByLabel('Client name', { exact: true })).toHaveValue('Before Quick Edit')
  await page.getByLabel('Client name', { exact: true }).fill('')
  await returnToClientReview(page)
  await expect(stepHeading(page, 'General Information')).toBeVisible()
  await expect(page.getByLabel('Client name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Client name', { exact: true }).fill('After Quick Edit')
  await returnToClientReview(page)
  await expect(stepHeading(page, 'Review & Confirm')).toBeVisible()
  await expect(clientSummary(page, 'General Information')).toContainText('After Quick Edit')
  await expect(clientSummary(page, 'General Information')).toContainText('Keep account remark')
  expect(await page.evaluate(key => localStorage.getItem(key), DB_KEY)).toBe(before)
  await createClient(page, 'After Quick Edit')
  const saved = await savedClient(page, 'After Quick Edit')
  expect(saved.client.trainerId).toBe(trainerId)
  expect(saved.client.remarks).toBe('Keep account remark')
  expect(saved.count).toBe(1)
})

test('M3 client summary scheduling edit revalidates availability and matching instead of saving stale choices', async ({ page }) => {
  await beginClient(page, 'Review Schedule Client')
  await finishMatching(page)
  await reviewClient(page)
  await page.getByRole('button', { name: 'Edit Package & Preferences', exact: true }).click()
  await page.getByLabel('PT Package', { exact: true }).selectOption('package-24')
  await page.getByLabel('Weekly frequency', { exact: true }).selectOption('2')
  await returnToClientReview(page)
  await expect(stepHeading(page, 'Client Availability')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('two possible days')
  await addPreference(page, ['Wednesday'])
  await returnToClientReview(page)
  await expect(stepHeading(page, 'Trainer Matching')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Fixed Weekly Schedule', { exact: true }).locator('div')).toHaveCount(2)
  await returnToClientReview(page)
  await expect(stepHeading(page, 'Review & Confirm')).toBeVisible()
  await expect(clientSummary(page, 'Package & Preferences')).toContainText('Twice per week')
  await expect(clientSummary(page, 'Trainer Matching')).toContainText('Wednesday')
  await createClient(page, 'Review Schedule Client')
  expect((await savedClient(page, 'Review Schedule Client')).sessions).toHaveLength(24)
})

test('M3 Couple summary shows both people and preserves person-specific edits through final creation', async ({ page }) => {
  await page.goto('/#/clients/new')
  await page.getByLabel('Client type', { exact: true }).selectOption('Couple')
  await page.getByLabel('Client 1 name', { exact: true }).fill('Review Alpha')
  await fillClientRequiredFields(page, 'Client 1')
  await page.getByLabel('Client 1 health or limitation notes', { exact: true }).fill('Alpha notes')
  await page.getByRole('button', { name: 'Client 2', exact: true }).click()
  await page.getByLabel('Client 2 name', { exact: true }).fill('Review Beta')
  await fillClientRequiredFields(page, 'Client 2')
  await page.getByLabel('Client 2 health or limitation notes', { exact: true }).fill('Beta notes')
  await continueTo(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await finishMatching(page)
  await reviewClient(page)
  await expect(clientSummary(page, 'General Information')).toContainText('Alpha notes')
  await expect(clientSummary(page, 'General Information')).toContainText('Beta notes')
  await page.getByRole('button', { name: 'Edit General Information', exact: true }).click()
  await page.getByRole('button', { name: 'Client 2', exact: true }).click()
  await page.getByLabel('Client 2 health or limitation notes', { exact: true }).fill('Beta changed notes')
  await returnToClientReview(page)
  await expect(clientSummary(page, 'General Information')).toContainText('Beta changed notes')
  await createClient(page, 'Review Alpha & Review Beta')
  expect((await savedClient(page, 'Review Alpha & Review Beta')).client.people.map(person => person.healthNotes))
    .toEqual(['Alpha notes', 'Beta changed notes'])
})
