import { expect, test } from '@playwright/test'
import { seed } from '../src/data/seed.js'
import { DEFAULT_EXERCISES } from '../src/app/exerciseCatalog.js'
const KEY = 'fitfinity-m2-demo-db-v4'
const movement = DEFAULT_EXERCISES[0]
async function start(page, route = 'exercises', custom = null) {
  const data = structuredClone(seed)
  data.sessions = [{ ...data.sessions[0], id: 'library-session', clientId: 'c1', trainerId: 't1', status: 'planned', date: '2099-09-06', from: '10:00', to: '11:00', exercisePlan: [{ id: 'historical', name: movement.name, weight: '10 kg', reps: '8', rounds: '2', rest: '60 sec', customDetails: [] }] }]
  if (custom) data.exerciseLibrary = custom
  await page.addInitScript(({ key, data }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, { key: KEY, data })
  await page.goto(`/#/${route}`)
}
const readDb = page => page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
const go = (page, path) => page.evaluate(path => { location.hash = `#/${path}` }, path)
const button = (page, name) => page.getByRole('button', { name, exact: true })
async function save(page, name) {
  await button(page, name).click()
  const dialog = page.getByRole('dialog', { name: `${name}?`, exact: true })
  await expect(dialog).toBeVisible()
  await button(dialog, name).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.library-form fieldset[disabled]')).toHaveCount(0)
  const errors = await page.locator('.library-form > [role="alert"]').allTextContents()
  expect(errors, `Exercise save failed: ${errors.join(' ')}`).toEqual([])
}
async function create(page, name = 'M3 Band Row') {
  await button(page, 'Add Exercise').click()
  await page.getByRole('textbox', { name: 'Exercise name', exact: true }).fill(name)
  await page.getByRole('combobox', { name: 'Category', exact: true }).selectOption('Upper Body')
  await page.getByLabel('Description', { exact: true }).fill('Keep elbows close.')
  await save(page, 'Create Exercise')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  return (await readDb(page)).exerciseLibrary.find(item => item.name === name)
}
const noOverflow = async page => expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)

test('M3 exercise creation and editing work when the browser does not expose randomUUID', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(crypto, 'randomUUID', { value: undefined, configurable: true })
  })
  await start(page)
  expect(await page.evaluate(() => typeof crypto.randomUUID)).toBe('undefined')
  const created = await create(page, 'M3 HTTP Preview')
  await button(page, 'Edit Exercise').click()
  await page.getByLabel('Description', { exact: true }).fill('Edited during device preview.')
  await save(page, 'Save Exercise')
  await expect(page.locator('.library-summary')).toContainText('Edited during device preview.')
  const db = await readDb(page)
  expect(db.exerciseLibrary.find(item => item.name === 'M3 HTTP Preview').id).toBe(created.id)
  expect(db.messages.filter(message => message.exerciseId === created.id)).toHaveLength(2)
})

test('M3 owner exercise library retains 49 exercises, six categories, compact pages and combined filters', async ({ page }) => {
  await start(page)
  await expect(page.locator('.sidebar nav').getByRole('button', { name: 'Exercise Library', exact: true })).toBeEnabled()
  await expect(page.locator('.library-row')).toHaveCount(10)
  await expect(page.getByText('49 exercises', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Exercise category').locator('option')).toHaveCount(7)
  await button(page, 'Next').click(); await expect(page.getByText('Page 2 of 5')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search exercises' }).fill('smith')
  await expect(page.getByText('Smith chest press', { exact: true })).toBeVisible()
  await expect(page.getByText('Page 2 of 5')).toHaveCount(0)
  await page.getByLabel('Exercise category').selectOption('Cardio')
  await expect(page.getByText('No exercises match your filters.')).toBeVisible()
  await page.getByRole('searchbox').fill(''); await page.getByLabel('Exercise category').selectOption('')
  await page.getByLabel('Exercise status').selectOption('inactive')
  await expect(page.getByText('0 exercises', { exact: true })).toBeVisible()
  await noOverflow(page)
})
test('M3 owner creates an exercise through confirmation and can use it in a session immediately', async ({ page }) => {
  await start(page); const before = await readDb(page)
  const saved = await create(page)
  const after = await readDb(page)
  expect(after.exerciseLibrary).toHaveLength(50); expect(after.sessions).toEqual(before.sessions)
  expect(after.messages.at(-1)).toMatchObject({ exerciseId: saved.id, read: false, recipientRole: 'owner' })
  await expect(page.locator('.library-summary')).toContainText('Keep elbows close.')
  await go(page, 'sessions/library-session')
  await button(page, 'Edit exercise plan').click()
  await page.getByRole('combobox', { name: 'Exercise 1 name' }).click()
  await page.getByLabel('Search exercise 1').fill('M3 Band Row')
  await button(page, 'M3 Band Row').click()
  await page.locator('.exercise-plan-panel').getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save exercise plan?' }).getByRole('button', { name: 'Save Plan' }).click()
  await expect(page.getByLabel('Exercise plan', { exact: true })).toContainText('M3 Band Row')
  expect((await readDb(page)).sessions[0].exercisePlan[0].name).toBe('M3 Band Row')
})
test('M3 exercise rename and deactivation preserve saved session names and allow reactivation', async ({ page }) => {
  await start(page, `exercises/${movement.id}`); const before = await readDb(page)
  await button(page, 'Edit Exercise').click()
  await page.getByRole('textbox', { name: 'Exercise name', exact: true }).fill('M3 Renamed Movement')
  await save(page, 'Save Exercise')
  await expect(page.getByRole('heading', { name: 'M3 Renamed Movement' })).toBeVisible()
  await save(page, 'Deactivate Exercise')
  await expect(page.locator('.section-head .status-badge')).toHaveText('Inactive')
  expect((await readDb(page)).sessions).toEqual(before.sessions)
  await go(page, 'sessions/library-session')
  await expect(page.getByLabel('Exercise plan', { exact: true })).toContainText(movement.name)
  await button(page, 'Edit exercise plan').click()
  await expect(page.getByRole('combobox', { name: 'Exercise 1 name' })).toContainText(movement.name)
  await page.getByRole('combobox', { name: 'Exercise 1 name' }).click()
  await expect(button(page, 'M3 Renamed Movement')).toHaveCount(0)
  await page.locator('.exercise-edit-actions').getByRole('button', { name: 'Cancel', exact: true }).click()
  await go(page, 'exercises'); await page.getByLabel('Exercise status').selectOption('inactive')
  await button(page, 'View exercise M3 Renamed Movement').click()
  await save(page, 'Reactivate Exercise')
  await expect(page.locator('.section-head .status-badge')).toHaveText('Active')
  expect((await readDb(page)).sessions).toEqual(before.sessions)
})
test('M3 exercise draft validation, cancelled save and cancelled navigation do not write data', async ({ page }) => {
  await start(page, 'exercises/new'); const before = await readDb(page)
  await button(page, 'Create Exercise').click()
  await expect(page.getByRole('textbox', { name: 'Exercise name', exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('textbox', { name: 'Exercise name', exact: true }).fill(movement.name)
  await button(page, 'Create Exercise').click(); await expect(page.getByText('This exercise name is already in use.')).toBeVisible()
  await page.getByRole('textbox', { name: 'Exercise name', exact: true }).fill('M3 Draft')
  await button(page, 'Create Exercise').click()
  await page.getByRole('dialog', { name: 'Create Exercise?' }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await button(page, 'Back to Exercise Library').click()
  await page.getByRole('dialog', { name: 'Leave this edit?' }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Exercise name', exact: true })).toHaveValue('M3 Draft')
  expect(await readDb(page)).toEqual(before)
  await noOverflow(page)
})
test('M3 exercise photo persists after refresh and can be replaced by a video then removed', async ({ page }) => {
  await start(page, 'exercises/new')
  await page.getByRole('textbox', { name: 'Exercise name', exact: true }).fill('M3 Reference')
  await page.getByLabel('Photo / video', { exact: true }).setInputFiles({ name: 'reference.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByRole('img', { name: 'Exercise reference' })).toBeVisible()
  await save(page, 'Create Exercise')
  await expect(page.getByRole('heading', { name: 'M3 Reference' })).toBeVisible()
  await page.reload()
  const photo = page.getByRole('img', { name: 'Exercise reference' })
  await expect(photo).toBeVisible(); await expect.poll(() => photo.evaluate(img => img.naturalWidth)).toBeGreaterThan(0)
  await button(page, 'Edit Exercise').click()
  await page.getByLabel('Photo / video', { exact: true }).setInputFiles('tests/fixtures/silent-one-second.webm')
  await save(page, 'Save Exercise')
  await expect(page.locator('.library-summary')).toContainText('silent-one-second.webm')
  await expect(page.locator('.library-media-preview video')).toHaveAttribute('src', /^blob:/)
  const record = (await readDb(page)).exerciseLibrary.find(item => item.name === 'M3 Reference')
  expect(record.media.type).toBe('video/webm')
  await button(page, 'Edit Exercise').click(); await button(page, 'Remove Attachment').click()
  await save(page, 'Save Exercise')
  await expect(page.locator('.library-summary')).toContainText('No attachment')
  expect((await readDb(page)).exerciseLibrary.find(item => item.id === record.id).media).toBeNull()
  await noOverflow(page)
})
test('M3 library message opens the correct exercise summary and Back returns to Messages', async ({ page }) => {
  await start(page); const saved = await create(page)
  await go(page, 'messages')
  await button(page, 'Open Exercise created: M3 Band Row').click()
  const dialog = page.getByRole('dialog', { name: 'Exercise created: M3 Band Row', exact: true })
  await expect(dialog.getByRole('button', { name: /^View Client/ })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'View Exercise · M3 Band Row', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`#/exercises/${saved.id}$`))
  await expect(page.getByRole('heading', { name: 'M3 Band Row', exact: true })).toBeVisible()
  await page.goBack(); await expect(page.getByRole('heading', { name: 'Messages', exact: true })).toBeVisible()
})
test('M3 trainers can select active managed exercises but cannot open owner library management', async ({ page }) => {
  const custom = [{ ...movement, id: 'added', name: 'M3 Active', category: 'Core' }, { ...movement, id: 'inactive', name: 'M3 Inactive', status: 'inactive' }, ...DEFAULT_EXERCISES]
  await start(page, 'dashboard', custom)
  const menu = page.locator('.profile-menu')
  if (await menu.locator('summary').isVisible()) await menu.locator('summary').click()
  await page.locator('.role-switcher select').selectOption('u-marcus')
  await expect(page.locator('.sidebar nav').getByRole('button', { name: 'Exercise Library', exact: true })).toHaveCount(0)
  await go(page, 'exercises/new'); await expect(page.getByText('Exercise library management is available to the owner.')).toBeVisible()
  await expect(button(page, 'Create Exercise')).toHaveCount(0)
  await go(page, 'sessions/library-session'); await button(page, 'Edit exercise plan').click()
  await page.getByRole('combobox', { name: 'Exercise 1 name' }).click()
  await page.getByLabel('Search exercise 1').fill('M3')
  await expect(button(page, 'M3 Active')).toBeVisible(); await expect(button(page, 'M3 Inactive')).toHaveCount(0)
})
