import { expect, test, selectDemoIdentity } from './fixtures.js'

const KEY = 'fitfinity-m2-demo-db-v4'
const heading = (page, name) => page.getByRole('heading', { level: 2, name, exact: true })
const next = (page, name) => page.getByRole('button', { name: `Continue to ${name}`, exact: true }).click()
const back = (page, name) => page.getByRole('button', { name: `Back to ${name}`, exact: true }).click()

async function begin(page, name = 'M3 New Trainer', email = 'm3-trainer@example.com') {
  await page.goto('/#/trainers/new')
  await page.getByLabel('Trainer name', { exact: true }).fill(name)
  await page.getByLabel('Trainer email', { exact: true }).fill(email)
  await page.getByLabel('Trainer gender', { exact: true }).selectOption('Female')
  await page.getByLabel('Trainer type', { exact: true }).fill('Personal')
}
async function block(page, day = 'Sunday', from = '10:00', to = '12:00') {
  await page.getByRole('button', { name: day, exact: true }).click()
  await page.getByLabel('Availability from', { exact: true }).fill(from)
  await page.getByLabel('Availability to', { exact: true }).fill(to)
  await page.getByRole('button', { name: 'Add Time', exact: true }).click()
}
async function ready(page) {
  await next(page, 'Training & Rates')
  await next(page, 'Trainer Availability')
  await block(page)
  await next(page, 'Owner Approval Needed')
}
async function reviewTrainer(page) {
  if (!(await heading(page, 'Review & Confirm').isVisible())) await next(page, 'Review & Confirm')
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
}
async function confirm(page, name) {
  await reviewTrainer(page)
  await page.getByRole('button', { name: 'Create Trainer', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: `Create ${name}?`, exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Create Trainer', exact: true }).click()
}
async function saved(page, email = 'm3-trainer@example.com') {
  return page.evaluate(({ key, email }) => {
    const state = JSON.parse(localStorage.getItem(key))
    const trainer = state.trainers.find(item => item.email === email)
    return { trainer, count: state.trainers.filter(item => item.email === email).length,
      user: state.users.find(item => item.trainerId === trainer.id),
      messages: state.messages.filter(item => item.trainerId === trainer.id) }
  }, { key: KEY, email })
}
async function tab(page, name) {
  const menu = page.locator('.profile-menu')
  await expect(menu).toBeVisible()
  if (await menu.locator('summary').isVisible()) await menu.locator('summary').click()
  await menu.getByRole('button', { name, exact: true }).click()
}
async function noOverflow(page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0)
}

test('M3 Add Trainer shows one validated section, required fields and default rates', async ({ page }) => {
  await page.goto('/#/trainers')
  await page.getByRole('button', { name: 'Add New Trainer', exact: true }).click()
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await expect(page.locator('.trainer-onboarding .panel')).toHaveCount(1)
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Trainer phone country code', { exact: true })).toHaveValue('+65')
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveAttribute('aria-required', 'true')
  await expect(page.getByLabel('Trainer birthday', { exact: true })).not.toHaveAttribute('required')
  await next(page, 'Training & Rates')
  await expect(heading(page, 'General Information')).toBeVisible()
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Trainer name', { exact: true }).fill('Validation Trainer')
  await page.getByLabel('Trainer email', { exact: true }).fill('invalid')
  await page.getByLabel('Trainer gender', { exact: true }).selectOption('Female')
  await page.getByLabel('Trainer type', { exact: true }).fill('Personal')
  await next(page, 'Training & Rates')
  await expect(page.getByLabel('Trainer email', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Trainer email', { exact: true }).fill('validation@example.com')
  await next(page, 'Training & Rates')
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveValue('80')
  await expect(page.getByLabel('Off-peak session rate', { exact: true })).toHaveValue('55')
  await page.getByLabel('Peak session rate', { exact: true }).fill('-1')
  await next(page, 'Trainer Availability')
  await expect(heading(page, 'Training & Rates')).toBeVisible()
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
  await noOverflow(page)
})

test('M3 owner creates a trainer with rates, phone, availability, controls, identity and routed messages', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await begin(page)
  await page.getByLabel('Trainer phone country code', { exact: true }).selectOption('+60')
  await page.getByLabel('Trainer phone number', { exact: true }).fill('123456789')
  await next(page, 'Training & Rates')
  await page.getByLabel('Peak session rate', { exact: true }).fill('85.50')
  await page.getByLabel('Off-peak session rate', { exact: true }).fill('60')
  await next(page, 'Trainer Availability')
  await block(page)
  await next(page, 'Owner Approval Needed')
  for (const name of ['Availability changes', 'Session time changes', 'Trainer reassignment', 'Fixed weekly schedule changes']) {
    await expect(page.getByRole('checkbox', { name, exact: true })).toBeChecked()
  }
  await page.getByRole('checkbox', { name: 'Session time changes', exact: true }).uncheck()
  await confirm(page, 'M3 New Trainer')
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Leave this edit?', exact: true })).toHaveCount(0)
  const result = await saved(page)
  expect(result.count).toBe(1)
  expect(result.trainer).toMatchObject({ phone: '+60 123456789', birthday: '', rates: { peak: 85.5, offPeak: 60 }, status: 'active' })
  expect(result.trainer.availability.Sunday).toEqual([['10:00', '12:00']])
  expect(result.trainer.approvalNeeded.sessionTime).toBe(false)
  expect(result.user).toMatchObject({ role: 'trainer', status: 'active', trainerId: result.trainer.id })
  expect(result.messages).toHaveLength(2)
  expect(result.messages.every(message => message.read === false)).toBe(true)
  await tab(page, 'Availability')
  await expect(heading(page, 'Approved Availability')).toBeVisible()
  await expect(page.locator('.availability-block')).toContainText('10:00am–12:00pm')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('M3 trainer reset and Back preserve other sections, rates and controls without saving', async ({ page }) => {
  await begin(page)
  await next(page, 'Training & Rates')
  await page.getByLabel('Peak session rate', { exact: true }).fill('90')
  await next(page, 'Trainer Availability')
  await block(page)
  await next(page, 'Owner Approval Needed')
  await page.getByRole('checkbox', { name: 'Availability changes', exact: true }).uncheck()
  await back(page, 'Trainer Availability')
  await page.getByRole('button', { name: 'Reset Availability', exact: true }).click()
  await expect(page.getByText('No availability blocks added yet.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Availability from', { exact: true })).toHaveValue('18:00')
  await expect(page.getByLabel('Availability to', { exact: true })).toHaveValue('19:00')
  await next(page, 'Owner Approval Needed')
  await expect(heading(page, 'Trainer Availability')).toBeVisible()
  await block(page, 'Monday', '18:00', '19:00')
  await back(page, 'Training & Rates')
  await expect(page.getByLabel('Peak session rate', { exact: true })).toHaveValue('90')
  await back(page, 'General Information')
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveValue('M3 New Trainer')
  await next(page, 'Training & Rates')
  await next(page, 'Trainer Availability')
  await next(page, 'Owner Approval Needed')
  await expect(page.getByRole('checkbox', { name: 'Availability changes', exact: true })).not.toBeChecked()
})

test('M3 trainer availability blocks overlaps and pending days and retains compact controls', async ({ page }) => {
  await begin(page)
  await next(page, 'Training & Rates')
  await next(page, 'Trainer Availability')
  await block(page)
  await block(page, 'Sunday', '11:00', '13:00')
  await expect(page.getByRole('alert')).toContainText('overlaps')
  await expect(page.getByLabel('Trainer availability blocks', { exact: true }).locator('.onboarding-preference-row')).toHaveCount(1)
  await page.getByLabel('Availability from', { exact: true }).fill('12:00')
  await page.getByRole('button', { name: 'Add Time', exact: true }).click()
  await expect(page.getByLabel('Trainer availability blocks', { exact: true }).locator('.onboarding-preference-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Monday', exact: true }).click()
  await next(page, 'Owner Approval Needed')
  await expect(page.getByRole('alert')).toContainText('Select Add Time')
  for (const name of ['Add Time', 'Reset Availability']) {
    const box = await page.getByRole('button', { name, exact: true }).boundingBox()
    expect(box.height).toBeLessThanOrEqual(40)
    expect(box.width).toBeLessThanOrEqual(name === 'Add Time' ? 100 : 150)
  }
  await noOverflow(page)
})

test('M3 trainer confirmation can be cancelled and retried without duplicate records', async ({ page }) => {
  await begin(page)
  await ready(page)
  await reviewTrainer(page)
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await page.getByRole('button', { name: 'Create Trainer', exact: true }).click()
  await page.getByRole('dialog', { name: 'Create M3 New Trainer?', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
  await confirm(page, 'M3 New Trainer')
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  expect((await saved(page)).count).toBe(1)
})

test('M3 duplicate trainer email leaves the draft recoverable and writes nothing until corrected', async ({ page }) => {
  await begin(page)
  await ready(page)
  await confirm(page, 'M3 New Trainer')
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  await begin(page, 'M3 Duplicate Trainer', 'M3-TRAINER@EXAMPLE.COM')
  await ready(page)
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await confirm(page, 'M3 Duplicate Trainer')
  await expect(page.locator('.notification-error').getByRole('alert')).toContainText('already belongs')
  await expect(page.locator('.onboarding-error[role="alert"]')).toContainText('already belongs')
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
  await page.getByRole('button', { name: 'Edit General Information', exact: true }).click()
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveValue('M3 Duplicate Trainer')
  await page.getByLabel('Trainer email', { exact: true }).fill('corrected@example.com')
  await page.getByRole('button', { name: 'Return to Review & Confirm', exact: true }).click()
  await confirm(page, 'M3 Duplicate Trainer')
  await expect(page.getByRole('heading', { name: 'M3 Duplicate Trainer', level: 1, exact: true })).toBeVisible()
  expect((await saved(page, 'corrected@example.com')).count).toBe(1)
})

test('M3 trainer Cancel uses the existing unsaved-edit guard and returns to Trainers', async ({ page }) => {
  await page.goto('/#/trainers')
  await page.getByRole('button', { name: 'Add New Trainer', exact: true }).click()
  await page.getByLabel('Trainer name', { exact: true }).fill('Keep Trainer Draft')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Leave this edit?', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Trainer name', { exact: true })).toHaveValue('Keep Trainer Draft')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await dialog.getByRole('button', { name: 'Leave Without Saving', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Trainers', level: 1, exact: true })).toBeVisible()
})

test('M3 a newly created trainer is immediately available in automatic client matching and demo identity', async ({ page }) => {
  await begin(page)
  await next(page, 'Training & Rates')
  await next(page, 'Trainer Availability')
  await block(page, 'Sunday', '14:00', '15:00')
  await next(page, 'Owner Approval Needed')
  await confirm(page, 'M3 New Trainer')
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  const trainer = await saved(page)
  await page.goto('/#/clients/new')
  await page.getByLabel('Client name', { exact: true }).fill('Assigned To New Trainer')
  await next(page, 'Package & Preferences')
  await page.getByLabel('Start date', { exact: true }).fill('2026-09-07')
  await next(page, 'Client Availability')
  await block(page, 'Sunday', '14:00', '15:00')
  await next(page, 'Trainer Matching')
  await expect(page.getByRole('button', { name: 'Find Matching Trainers', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Matched trainer', { exact: true })).toHaveValue(trainer.trainer.id)
  await next(page, 'Review & Confirm')
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
  await page.getByRole('button', { name: 'Create Client', exact: true }).click()
  await page.getByRole('dialog', { name: 'Create Assigned To New Trainer?', exact: true }).getByRole('button', { name: 'Create Client', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Assigned To New Trainer', level: 1, exact: true })).toBeVisible()
  await selectDemoIdentity(page, trainer.user.id)
  await expect(page.getByRole('heading', { name: 'Trainer Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { location.hash = '#/my-profile' })
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0)
  await expect(page.locator('.profile-menu button').filter({ hasText: 'Assigned Clients' })).toHaveCount(0)
  await page.evaluate(() => { location.hash = '#/clients' })
  await expect(page.getByRole('heading', { name: 'Clients', level: 1, exact: true })).toBeVisible()
  await expect(page.getByText('Assigned To New Trainer', { exact: true })).toBeVisible()
})

const trainerSummary = (page, title) => page.getByRole('region', { name: title, exact: true })
const returnToTrainerReview = page => page.getByRole('button', { name: 'Return to Review & Confirm', exact: true }).click()

test('M3 trainer summary shows all sections and saves the reviewed rate and approval quick edits once', async ({ page }) => {
  await begin(page)
  await page.getByLabel('Trainer phone number', { exact: true }).fill('9123 4567')
  await page.getByLabel('Trainer qualifications', { exact: true }).fill('ACE qualification')
  await ready(page)
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await expect(page.getByRole('button', { name: 'Create Trainer', exact: true })).toHaveCount(0)
  await reviewTrainer(page)
  await expect(page.getByLabel('Creation progress', { exact: true })).toHaveText('Step 5 of 5')
  await expect(trainerSummary(page, 'General Information')).toContainText('+65 9123 4567')
  await expect(trainerSummary(page, 'General Information')).toContainText('ACE qualification')
  await expect(trainerSummary(page, 'Training & Rates')).toContainText('S$80.00 / session')
  await expect(trainerSummary(page, 'Trainer Availability')).toContainText('Sunday · 10:00–12:00')
  for (const title of ['General Information', 'Training & Rates', 'Trainer Availability', 'Owner Approval Needed']) {
    await expect(page.getByRole('button', { name: `Edit ${title}`, exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: 'Edit Training & Rates', exact: true }).click()
  await page.getByLabel('Peak session rate', { exact: true }).fill('95.50')
  await returnToTrainerReview(page)
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
  await expect(trainerSummary(page, 'Training & Rates')).toContainText('S$95.50 / session')
  await page.getByRole('button', { name: 'Edit Owner Approval Needed', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Session time changes', exact: true }).uncheck()
  await returnToTrainerReview(page)
  await expect(trainerSummary(page, 'Owner Approval Needed')).toContainText('Direct action allowed')
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
  await confirm(page, 'M3 New Trainer')
  await expect(page.getByRole('heading', { name: 'M3 New Trainer', level: 1, exact: true })).toBeVisible()
  const result = await saved(page)
  expect(result.count).toBe(1)
  expect(result.trainer.rates.peak).toBe(95.5)
  expect(result.trainer.approvalNeeded.sessionTime).toBe(false)
})

test('M3 trainer summary General Information edit cannot return with an invalid required email', async ({ page }) => {
  await begin(page)
  await ready(page)
  await reviewTrainer(page)
  await page.getByRole('button', { name: 'Edit General Information', exact: true }).click()
  await page.getByLabel('Trainer email', { exact: true }).fill('')
  await returnToTrainerReview(page)
  await expect(heading(page, 'General Information')).toBeVisible()
  await expect(page.getByLabel('Trainer email', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Trainer email', { exact: true }).fill('review-changed@example.com')
  await returnToTrainerReview(page)
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
  await expect(trainerSummary(page, 'General Information')).toContainText('review-changed@example.com')
  await expect(trainerSummary(page, 'Trainer Availability')).toContainText('Sunday · 10:00–12:00')
})

test('M3 trainer summary availability quick edit checks pending blocks and preserves the other draft sections', async ({ page }) => {
  await begin(page)
  await ready(page)
  await page.getByRole('checkbox', { name: 'Availability changes', exact: true }).uncheck()
  await reviewTrainer(page)
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await page.getByRole('button', { name: 'Edit Trainer Availability', exact: true }).click()
  await page.getByRole('button', { name: 'Monday', exact: true }).click()
  await returnToTrainerReview(page)
  await expect(heading(page, 'Trainer Availability')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Select Add Time')
  await page.getByRole('button', { name: 'Add Time', exact: true }).click()
  await returnToTrainerReview(page)
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
  await expect(trainerSummary(page, 'Trainer Availability')).toContainText('Monday')
  await expect(trainerSummary(page, 'Trainer Availability')).toContainText('Sunday')
  await expect(trainerSummary(page, 'Owner Approval Needed')).toContainText('Direct action allowed')
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
})

test('M3 long form summary wraps without overflow and Cancel retains the whole draft when staying', async ({ page }) => {
  await begin(page)
  const longText = ('QualificationLineWithNoSpaces'.repeat(6) + '\n') + 'More details. '.repeat(35)
  await page.getByLabel('Trainer qualifications', { exact: true }).fill(longText)
  await ready(page)
  await reviewTrainer(page)
  await expect(trainerSummary(page, 'General Information')).toContainText(longText.trim())
  await noOverflow(page)
  for (const button of await page.locator('.onboarding-review-edit').all()) {
    const box = await button.boundingBox()
    expect(box.height).toBeLessThanOrEqual(40)
    expect(box.width).toBeLessThanOrEqual(80)
  }
  const before = await page.evaluate(key => localStorage.getItem(key), KEY)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Leave this edit?', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(heading(page, 'Review & Confirm')).toBeVisible()
  await expect(trainerSummary(page, 'General Information')).toContainText(longText.trim())
  expect(await page.evaluate(key => localStorage.getItem(key), KEY)).toBe(before)
})
