import { test, expect, selectDemoIdentity, mockPdfSharing } from './fixtures.js'
import { seed } from '../src/data/seed.js'
import { clientProfileDraft } from '../src/app/clientOnboarding.js'

const KEY = 'fitfinity-m2-demo-db-v4'
async function start(page, modify = () => {}) {
  const data = structuredClone(seed)
  modify(data)
  await page.clock.setFixedTime(new Date('2026-09-09T04:00:00Z'))
  await page.addInitScript(({ key, data }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, { key: KEY, data })
  await page.goto('/#/dashboard')
  await expect(page.getByRole('heading', { name: 'Owner Dashboard' })).toBeVisible()
}
async function tab(page, name) {
  const menu = page.locator('.profile-menu'), summary = menu.locator('summary')
  if (await summary.isVisible()) await summary.click()
  await menu.getByRole('button', { name, exact: true }).click()
}

test('M4 couple profile uses creation controls and persists each person without altering session records', async ({ page }) => {
  await start(page, data => {
    const client = data.clients.find(item => item.id === 'c2')
    client.people = clientProfileDraft(client, data.settings).people.map((person, index) => ({ ...person,
      name: index ? 'Mei Wong' : 'Daniel Wong', gender: index ? 'Female' : 'Male',
    }))
  })
  await page.goto('/#/clients/c2')
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const general = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'General Information', exact: true }) })
  await general.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(general.getByRole('combobox', { name: 'Client type', exact: true })).toBeDisabled()
  await expect(general.getByRole('combobox', { name: 'Client 1 gender', exact: true })).toHaveValue('Male')
  await general.getByLabel('Client 1 phone country code', { exact: true }).selectOption('+60')
  await general.getByLabel('Client 1 phone number', { exact: true }).fill('123456789')
  await general.getByRole('button', { name: 'Client 2', exact: true }).click()
  await general.getByRole('combobox', { name: 'Client 2 gender', exact: true }).selectOption('Prefer not to say')
  await general.getByLabel('Client 2 email', { exact: true }).fill('mei.updated@example.com')
  await general.getByLabel('Client 2 birthday', { exact: true }).fill('1990-06-15')
  await general.getByRole('combobox', { name: 'Client 2 emergency contact relationship', exact: true }).selectOption('Sibling')
  await general.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save client information?' }).getByRole('button', { name: 'Save Changes', exact: true }).click()
  await expect(general.getByRole('button', { name: 'Edit', exact: true })).toBeEnabled()
  await page.reload()
  await general.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(general.getByLabel('Client 1 phone country code', { exact: true })).toHaveValue('+60')
  await expect(general.getByLabel('Client 1 phone number', { exact: true })).toHaveValue('123456789')
  await general.getByRole('button', { name: 'Client 2', exact: true }).click()
  await expect(general.getByLabel('Client 2 gender', { exact: true })).toHaveValue('Prefer not to say')
  await expect(general.getByLabel('Client 2 email', { exact: true })).toHaveValue('mei.updated@example.com')
  await expect(general.getByLabel('Client 2 birthday', { exact: true })).toHaveValue('1990-06-15')
  await expect(general.getByLabel('Client 2 emergency contact relationship', { exact: true })).toHaveValue('Sibling')
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(after.sessions).toEqual(before.sessions)
  expect(after.packageCreditTransactions).toEqual(before.packageCreditTransactions)
  expect(after.clients.find(item => item.id === 'c2').package).toEqual(before.clients.find(item => item.id === 'c2').package)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('M4 trainer profile uses creation controls, blocks incomplete details and persists decimal rates', async ({ page }) => {
  await start(page)
  await page.goto('/#/trainers/t1')
  const general = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'General Information', exact: true }) })
  await general.getByRole('button', { name: 'Edit', exact: true }).click()
  const gender = general.getByRole('combobox', { name: 'Trainer gender', exact: true })
  await gender.selectOption('')
  await general.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(gender).toBeFocused()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await gender.selectOption('Male')
  await general.getByLabel('Trainer phone country code', { exact: true }).selectOption('+60')
  await general.getByLabel('Trainer phone number', { exact: true }).fill('123456789')
  await expect(general.getByLabel('Trainer birthday', { exact: true })).toHaveAttribute('type', 'date')
  await expect(general.getByLabel('Trainer type', { exact: true })).toHaveAttribute('list', 'trainer-type-options')
  await expect(general.getByLabel('Trainer qualifications', { exact: true })).toHaveJSProperty('tagName', 'TEXTAREA')
  await general.getByLabel('Trainer qualifications', { exact: true }).fill('Updated certification\nFirst aid')
  await general.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save trainer information?' }).getByRole('button', { name: 'Save Changes', exact: true }).click()
  await expect(general.getByRole('button', { name: 'Edit', exact: true })).toBeEnabled()
  const rates = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Training & Rates', exact: true }) })
  await rates.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(rates.getByLabel('Peak rate', { exact: true })).toHaveAttribute('step', '0.01')
  await rates.getByLabel('Peak rate', { exact: true }).fill('')
  await rates.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(rates.getByRole('alert')).toContainText('non-negative peak rate')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await rates.getByLabel('Peak rate', { exact: true }).fill('80.25')
  await rates.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save trainer rates?' }).getByRole('button', { name: 'Save Rates', exact: true }).click()
  await expect(rates.getByRole('button', { name: 'Edit', exact: true })).toBeEnabled()
  await page.reload()
  await expect(rates).toContainText('$80.25 / session')
  await general.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(general.getByLabel('Trainer phone country code', { exact: true })).toHaveValue('+60')
  await expect(general.getByLabel('Trainer phone number', { exact: true })).toHaveValue('123456789')
  await expect(general.getByLabel('Trainer qualifications', { exact: true })).toHaveValue('Updated certification\nFirst aid')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

for (const [route, heading, add] of [['clients', 'Clients', 'Add New Client'], ['trainers', 'Trainers', 'Add New Trainer']]) {
  test(`M4 ${route} Add stays at the top right on desktop, tablet and phone`, async ({ page }) => {
    await start(page)
    await page.goto(`/#/${route}`)
    const title = page.getByRole('heading', { name: heading, exact: true }), button = page.getByRole('button', { name: add, exact: true })
    await expect(title).toBeVisible()
    const head = await page.locator('.directory-page-head').boundingBox(), addBox = await button.boundingBox(), titleBox = await title.boundingBox()
    expect(addBox.x).toBeGreaterThan(titleBox.x)
    expect(Math.abs(addBox.x + addBox.width - head.x - head.width)).toBeLessThan(2)
    expect(addBox.y).toBeLessThan(titleBox.y + titleBox.height)
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  })
}

test('M4 adds a Package using prefilled steps two to five and keeps separate progress after reload', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  await expect(page.getByRole('heading', { name: 'Additional Packages', exact: true })).toHaveCount(0)
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  await page.getByRole('button', { name: 'Add Package', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add Package', exact: true })
  await expect(dialog.getByLabel('PT Package', { exact: true })).toBeVisible()
  await expect(dialog.getByLabel('Client name', { exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('Matched trainer', { exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('Start date', { exact: true })).toHaveAttribute('min', '2026-11-15')
  await expect(dialog.getByLabel('Start date', { exact: true })).toHaveValue('2026-11-16')
  await dialog.getByLabel('Start date', { exact: true }).fill('2026-11-12')
  await dialog.getByRole('button', { name: 'Continue to Client Availability' }).click()
  await expect(dialog.getByRole('alert')).toContainText('after the existing packages end')
  await dialog.getByLabel('Start date', { exact: true }).fill('2027-01-04')
  await dialog.getByRole('button', { name: 'Continue to Client Availability' }).click()
  await expect(dialog.getByLabel('Client availability blocks')).toContainText('Monday')
  await dialog.getByRole('button', { name: 'Continue to Trainer Matching' }).click()
  await expect(dialog.getByLabel('Matched trainer', { exact: true })).toHaveValue('t1')
  await expect(dialog.getByLabel('Fixed Weekly Schedule', { exact: true })).toContainText('18:00–19:00')
  await dialog.getByRole('button', { name: 'Continue to Review & Confirm' }).click()
  await dialog.getByRole('button', { name: 'Add Package', exact: true }).click()
  const review = page.getByRole('dialog', { name: 'Add package for Amanda Lim?' })
  await expect(review).toContainText('12 sessions')
  await review.getByRole('button', { name: 'Add Package', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByText('Package added.', { exact: true })).toBeVisible()
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const old = before.clients.find(item => item.id === 'c1'), client = after.clients.find(item => item.id === 'c1')
  expect(after.clients.length).toBe(before.clients.length)
  expect(client.package).toEqual(old.package)
  expect(client.packageHistory).toEqual(old.packageHistory)
  expect(client.additionalPackages).toHaveLength(1)
  expect(client.additionalPackages[0].used).toBe(0)
  expect(after.sessions.filter(item => item.packageId === client.additionalPackages[0].id)).toHaveLength(12)
  const additional = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Additional Packages', exact: true }) })
  await expect(additional).toContainText('04 Jan 2027')
  const current = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Current Package', exact: true }) })
  expect((await additional.boundingBox()).y).toBeGreaterThan((await current.boundingBox()).y)
  await tab(page, 'Progress')
  const list = page.getByLabel('Progress packages', { exact: true })
  await expect(list.locator(`[data-package-id="${client.package.id}"]`)).toContainText('Current')
  await expect(list.locator(`[data-package-id="${client.additionalPackages[0].id}"]`)).toHaveCount(0)
  await expect(page.getByText('Unassigned Historical Records', { exact: true })).toHaveCount(0)
  await list.locator(`[data-package-id="${client.packageHistory[0].id}"]`).getByRole('button', { name: 'View', exact: true }).click()
  await expect(page.getByText('No completed exercise loads yet.')).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(new RegExp(`/progress/${client.packageHistory[0].id}$`))
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await list.locator(`[data-package-id="${client.package.id}"]`).getByRole('button', { name: 'View', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Show Goblet Squat progress chart', exact: true })).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(new RegExp(`/progress/${client.package.id}$`))
  await expect(page.getByRole('button', { name: 'Show Goblet Squat progress chart', exact: true })).toBeVisible()
})

test('M4 Progress package drill-in preserves independent package, exercise and audit pages through reload and Back', async ({ page }) => {
  await start(page, data => {
    const client = data.clients[0], sample = data.sessions.find(item => item.id === 's0')
    client.packageHistory = Array.from({ length: 12 }, (_, index) => ({ ...client.packageHistory[0],
      id: `report-purchase-${index}`, name: `Past purchase ${index + 1}`, startDate: `${2014 + index}-01-01`, endDate: `${2014 + index}-03-31`, used: 1,
    }))
    data.sessions.push({ ...sample, id: 'many-exercises', packageId: 'report-purchase-2', date: '2016-01-04',
      exerciseResults: Array.from({ length: 12 }, (_, index) => ({ id: `measured-${index}`, name: `Measured exercise ${index + 1}`, loadKg: index + 10, sets: 3, reps: 8 })),
    })
    data.progressReportEvents = Array.from({ length: 12 }, (_, index) => ({ id: `report-event-${index}`, clientId: 'c1', packageId: 'report-purchase-2',
      kind: 'pdf_export', at: `2026-09-${String(index + 1).padStart(2, '0')}T04:00:00.000Z`, by: { id: 'u-owner', name: 'Owner' },
    }))
  })
  await page.goto('/#/clients/c1')
  await tab(page, 'Progress')
  const packages = page.getByLabel('Progress packages', { exact: true })
  await expect(packages.locator('article')).toHaveCount(10)
  await expect(page.getByRole('heading', { name: 'Strength Progress', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(packages.locator('article')).toHaveCount(3)
  await packages.locator('[data-package-id="report-purchase-2"]').getByRole('button', { name: 'View', exact: true }).click()
  await expect(page).toHaveURL(/\/progress\/report-purchase-2$/)
  const exercises = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Strength Progress', exact: true }) })
  await expect(exercises.locator('.strength-progress-item')).toHaveCount(10)
  await exercises.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(exercises.locator('.strength-progress-item')).toHaveCount(2)
  await exercises.getByRole('button', { name: 'Show Measured exercise 11 progress chart', exact: true }).click()
  await page.getByRole('button', { name: 'View Export/WhatsApp History', exact: true }).click()
  const history = page.getByLabel('Export/WhatsApp history', { exact: true })
  await expect(history.locator('article')).toHaveCount(10)
  await history.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(history.locator('article')).toHaveCount(2)
  await expect(exercises).toContainText('Page 2 of 2')
  await page.reload()
  await expect(history.locator('article')).toHaveCount(2)
  await expect(history).toContainText('Page 2 of 2')
  await expect(exercises.getByRole('button', { name: 'Hide Measured exercise 11 progress chart', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(packages.locator('article')).toHaveCount(3)
  await expect(page.getByText('Page 2 of 2', { exact: true })).toBeVisible()
  await page.goForward()
  await expect(history).toContainText('Page 2 of 2')
  await expect(exercises).toContainText('Page 2 of 2')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('M4 client session date ranges and trainer assigned-client pagination survive detail Back and reload', async ({ page }) => {
  await start(page, data => {
    const client = data.clients[0], sample = data.sessions.find(item => item.id === 's0')
    data.clients = [client, ...Array.from({ length: 12 }, (_, index) => ({ ...structuredClone(client), id: `assigned-${index}`, name: `Assigned ${index + 1}`, email: `assigned-${index}@example.com` }))]
    data.sessions = ['history', 'upcoming'].flatMap(kind => Array.from({ length: 22 }, (_, index) => ({ ...sample,
      id: `${kind}-${index}`, date: `2026-${kind === 'history' ? '08' : '10'}-${String(index + 1).padStart(2, '0')}`,
      status: kind === 'history' ? 'completed' : 'planned', acknowledgement: kind === 'history' ? sample.acknowledgement : null,
    })))
  })
  await page.goto('/#/clients/c1')
  for (const [title, month] of [['Session History', '08'], ['Upcoming Sessions', '10']]) {
    await tab(page, title)
    const list = page.getByLabel(title, { exact: true })
    await expect(list.locator('article')).toHaveCount(10)
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(page.getByText('Page 2 of 3', { exact: true })).toBeVisible()
    await page.getByLabel(`${title} from`, { exact: true }).fill(`2026-${month}-05`)
    await page.getByLabel(`${title} to`, { exact: true }).fill(`2026-${month}-16`)
    await expect(page.getByText('Page 1 of 2', { exact: true })).toBeVisible()
    await expect(list.locator('article')).toHaveCount(10)
    await expect(list).toContainText(`${title === 'Session History' ? '16 Aug' : '05 Oct'} 2026`)
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(list.locator('article')).toHaveCount(2)
    await expect(list).toContainText(`${title === 'Session History' ? '05 Aug' : '16 Oct'} 2026`)
    await list.getByRole('button', { name: 'View', exact: true }).first().click()
    await expect(page.getByRole('heading', { name: 'Session Overview' })).toBeVisible()
    await page.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(list.locator('article')).toHaveCount(2)
    await page.reload()
    await expect(page.getByLabel(`${title} from`, { exact: true })).toHaveValue(`2026-${month}-05`)
    await expect(page.getByLabel(`${title} to`, { exact: true })).toHaveValue(`2026-${month}-16`)
    await expect(list.locator('article')).toHaveCount(2)
  }
  await tab(page, 'Session History')
  await expect(page.getByLabel('Session History', { exact: true }).locator('article')).toHaveCount(2)
  await page.goto('/#/trainers/t1')
  await tab(page, 'Assigned Clients')
  const assigned = page.getByLabel('Assigned client list', { exact: true })
  await expect(assigned.locator('.quick-row')).toHaveCount(10)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(assigned.locator('.quick-row')).toHaveCount(3)
  await assigned.getByRole('button', { name: 'View', exact: true }).first().click()
  await expect(page).toHaveURL(/\/clients\/assigned-/)
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(assigned.locator('.quick-row')).toHaveCount(3)
  await page.reload()
  await expect(assigned.locator('.quick-row')).toHaveCount(3)
  await page.getByLabel('Search assigned clients', { exact: true }).fill('Amanda')
  await expect(assigned.locator('.quick-row')).toHaveCount(1)
  await expect(assigned).toContainText('Amanda Lim')
  await expect(page.getByRole('navigation', { name: 'List pages', exact: true })).toHaveCount(0)
})

test('M4 inactive profiles and remaining sessions stay visible and read-only for both roles', async ({ page }) => {
  await start(page, data => { data.clients[0].status = 'inactive' })
  for (const user of ['u-owner', 'u-marcus']) {
    await page.goto('/#/dashboard')
    await selectDemoIdentity(page, user)
    await page.goto('/#/clients')
    await page.getByLabel('Search client', { exact: true }).fill('Amanda')
    await page.getByRole('button', { name: 'View Amanda Lim' }).click()
    await expect(page.getByLabel('Client status')).toContainText('Inactive')
    await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0)
    await tab(page, 'Package')
    await expect(page.getByRole('button', { name: 'Add Package', exact: true })).toHaveCount(0)
    await tab(page, 'Upcoming Sessions')
    await page.getByLabel('Upcoming Sessions').getByRole('button', { name: 'View', exact: true }).first().click()
    await expect(page.getByText('Client inactive', { exact: true })).toBeVisible()
    const edits = page.getByRole('button', { name: /^(Edit|Request Time Change|Request Trainer Change)$/ })
    for (const edit of await edits.all()) await expect(edit).toBeDisabled()
    await expect(page.getByRole('button', { name: 'Client Signature', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Export Summary', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Upcoming Sessions', exact: true })).toBeVisible()
  }
})

test('M4 package progress excludes older purchases from both visible loads and PDF share payload', async ({ page }) => {
  await start(page, data => {
    const client = data.clients[0]
    const original = data.sessions.find(item => item.id === 's0')
    data.sessions = data.sessions.filter(item => item.clientId !== client.id)
    data.sessions.push(...[
      { id: 'past-progress-session', date: '2026-03-01', load: 200, packageId: client.packageHistory[0].id },
      { id: 'current-progress-session', date: '2026-09-01', load: 25, packageId: client.package.id },
    ].map(item => ({ ...original, id: item.id, date: item.date, packageId: item.packageId,
      exerciseResults: [{ id: 'package-row', name: 'Package-specific row', loadKg: item.load, reps: 8, sets: 3 }],
    })))
  })
  await page.goto('/#/clients/c1')
  await tab(page, 'Progress')
  await page.getByLabel('Progress packages', { exact: true }).locator('[data-package-id="client-package-c1"]').getByRole('button', { name: 'View', exact: true }).click()
  const row = page.getByRole('button', { name: 'Show Package-specific row progress chart', exact: true })
  await expect(row).toContainText('25 kg')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByLabel('Progress packages', { exact: true }).locator('[data-package-id="c1-package-2026-1"]').getByRole('button', { name: 'View', exact: true }).click()
  await expect(row).toContainText('200 kg')
  await page.goto('/#/clients')
  await page.goBack()
  await expect(page).toHaveURL(/\/progress\/c1-package-2026-1$/)
  await expect(row).toContainText('200 kg')
  await mockPdfSharing(page)
  await page.getByRole('button', { name: 'Share Progress Report via WhatsApp' }).click()
  await page.getByRole('dialog', { name: 'Share Progress Report' }).getByRole('button', { name: 'Share PDF', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const event = await page.evaluate(key => JSON.parse(localStorage.getItem(key)).progressReportEvents.at(-1), KEY)
  expect(event).toMatchObject({ clientId: 'c1', packageId: 'c1-package-2026-1', kind: 'pdf_share_opened' })
  expect((await page.evaluate(() => window.__pdfShares))[0]).toMatchObject({ type: 'application/pdf', images: 1, active: true })
})

test('M4 browser PDF fallback opens the generated PDF and reports blocked windows without inventing a share', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c1')
  await tab(page, 'Progress')
  await page.getByLabel('Progress packages', { exact: true }).locator('article').first().getByRole('button', { name: 'View', exact: true }).click()
  await mockPdfSharing(page, { supported: false })
  await page.getByRole('button', { name: 'Share Progress Report via WhatsApp' }).click()
  const dialog = page.getByRole('dialog', { name: 'Share Progress Report' })
  const open = dialog.getByRole('button', { name: 'Open PDF', exact: true })
  await expect(open).toBeVisible()
  // Stub the OS window boundary; capture the real generated PDF behind its URL.
  await page.evaluate(() => { window.open = url => { window.__openedReport = { url, active: navigator.userActivation.isActive }; return null } })
  await open.click()
  await expect(dialog.getByRole('alert')).toContainText('PDF window was blocked')
  const opened = await page.evaluate(async () => {
    const response = await fetch(window.__openedReport.url), blob = await response.blob()
    return { active: window.__openedReport.active, type: blob.type, header: (await blob.text()).slice(0, 9) }
  })
  expect(opened).toEqual({ active: true, type: 'application/pdf', header: '%PDF-1.4\n' })
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)).progressReportEvents ?? [], KEY)).toEqual([])
  await expect(dialog.getByRole('button', { name: 'Download PDF', exact: true })).toBeEnabled()
})

test('M4 package deactivation defaults to retention, freezes its session and allows later deletion', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  await page.getByRole('button', { name: 'Deactivate Package', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Deactivate Package?' })
  await expect(dialog.getByRole('checkbox')).not.toBeChecked()
  await dialog.getByRole('button', { name: 'Deactivate Package', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByText('No active current package.')).toBeVisible()
  const retained = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(retained.sessions).toEqual(before.sessions)
  const session = retained.sessions.find(item => item.clientId === 'c1' && item.status !== 'completed' && item.date > '2026-09-09')
  await page.goto(`/#/sessions/${session.id}`)
  await expect(page.getByText('Package inactive', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export Summary', exact: true })).toBeDisabled()
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  await page.getByRole('button', { name: /Delete Upcoming Sessions/ }).first().click()
  const cleanup = page.getByRole('dialog', { name: 'Delete Upcoming Package Sessions?' })
  await cleanup.getByRole('button', { name: 'Delete Sessions', exact: true }).click()
  await expect(cleanup).toHaveCount(0)
  await expect(page.getByText(/upcoming sessions deleted ·/)).toBeVisible()
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(after.sessions.some(item => item.id === session.id)).toBe(false)
  expect(after.sessions.filter(item => item.clientId !== 'c1' || item.status === 'completed' || item.date < '2026-09-09'))
    .toEqual(before.sessions.filter(item => item.clientId !== 'c1' || item.status === 'completed' || item.date < '2026-09-09'))
})

test('M4 deactivating a client freezes every package and retains owner-only cleanup after reload', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c1')
  await tab(page, 'Deactivate Client')
  await page.getByRole('dialog', { name: 'Deactivate Amanda Lim?' }).getByRole('button', { name: 'Deactivate Client', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Clients', exact: true })).toBeVisible()
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  await expect(page.getByRole('button', { name: 'Add Package', exact: true })).toHaveCount(0)
  const client = await page.evaluate(key => JSON.parse(localStorage.getItem(key)).clients.find(item => item.id === 'c1'), KEY)
  expect([client.package, ...client.packageHistory].every(item => item.status === 'inactive')).toBe(true)
  await page.reload()
  await page.getByRole('button', { name: /Delete Upcoming Sessions/ }).first().click()
  await page.getByRole('dialog', { name: 'Delete Upcoming Package Sessions?' }).getByRole('button', { name: 'Delete Sessions', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/#/dashboard')
  await selectDemoIdentity(page, 'u-marcus')
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  await expect(page.getByRole('button', { name: /Delete Upcoming Sessions|Add Package|Deactivate Package/ })).toHaveCount(0)
  await expect(page.getByText(/upcoming sessions deleted ·/)).toBeVisible()
})

test('M4 Add Package queues the selected trainer and weekly time without rewriting the current purchase or sessions', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c1')
  await tab(page, 'Package')
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const trainer = before.trainers.find(item => item.id !== 't1' && item.status === 'active' && item.availability.Monday?.length)
  const [from, to] = trainer.availability.Monday[0]
  await page.getByRole('button', { name: 'Add Package', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add Package', exact: true })
  await dialog.getByLabel('Start date', { exact: true }).fill('2027-01-04')
  await dialog.getByRole('button', { name: 'Continue to Client Availability' }).click()
  await dialog.getByRole('button', { name: 'Reset Availability' }).click()
  await dialog.getByRole('button', { name: 'Monday', exact: true }).click()
  await dialog.getByLabel('Availability from', { exact: true }).fill(from)
  await dialog.getByLabel('Availability to', { exact: true }).fill(to)
  await dialog.getByRole('button', { name: 'Add Time', exact: true }).click()
  await dialog.getByRole('button', { name: 'Continue to Trainer Matching' }).click()
  await dialog.getByLabel('Matched trainer', { exact: true }).selectOption(trainer.id)
  await dialog.getByRole('button', { name: 'Continue to Review & Confirm' }).click()
  await expect(dialog.getByLabel('Form summary')).toContainText(trainer.name)
  await dialog.getByRole('button', { name: 'Add Package', exact: true }).click()
  await page.getByRole('dialog', { name: 'Add package for Amanda Lim?' }).getByRole('button', { name: 'Add Package', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const client = after.clients.find(item => item.id === 'c1')
  const previous = before.clients.find(item => item.id === 'c1')
  expect(client.trainerId).toBe(previous.trainerId)
  expect(client.fixedWeeklySchedule).toEqual(previous.fixedWeeklySchedule)
  expect(client.package).toEqual(previous.package)
  expect(client.additionalPackages[0]).toMatchObject({ trainerId: trainer.id, fixedWeeklySchedule: [{ day: 'Monday', from, to }] })
  const added = after.sessions.filter(item => item.packageId === client.additionalPackages[0].id)
  expect(added).toHaveLength(12)
  expect(added.every(item => item.trainerId === trainer.id && item.from === from && item.to === to)).toBe(true)
  expect(after.sessions.filter(item => before.sessions.some(old => old.id === item.id))).toEqual(before.sessions)
})

test('M4 fixed weekly time changes update every eligible upcoming session and its scheduled duration', async ({ page }) => {
  await start(page, data => {
    data.sessions = data.sessions.filter(item => item.clientId === 'c1')
    for (const session of data.sessions) session.outcome = { durationMinutes: 60 }
  })
  await page.goto('/#/clients/c1')
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const panel = page.locator('.schedule-panel')
  await panel.getByRole('button', { name: 'Edit', exact: true }).click()
  await panel.getByLabel('Monday from', { exact: true }).fill('19:00')
  await panel.getByLabel('Monday to', { exact: true }).fill('20:15')
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save fixed weekly schedule?' }).getByRole('button', { name: 'Save Schedule', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Edit', exact: true })).toBeVisible()
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  const changed = before.sessions.filter(item => !['completed', 'cancelled'].includes(item.status) && item.date > '2026-09-09')
  expect(changed.length).toBeGreaterThan(1)
  for (const old of changed) expect(after.sessions.find(item => item.id === old.id)).toMatchObject({ date: old.date, trainerId: old.trainerId, from: '19:00', to: '20:15', outcome: { durationMinutes: 75 } })
  for (const old of before.sessions.filter(item => item.status === 'completed' || item.date < '2026-09-09')) expect(after.sessions.find(item => item.id === old.id)).toEqual(old)
})

test('M4 Add Package prefills a legacy 24-session choice instead of the first template', async ({ page }) => {
  await start(page)
  await page.goto('/#/clients/c2')
  await tab(page, 'Package')
  await page.getByRole('button', { name: 'Add Package', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add Package', exact: true })
  await expect(dialog.getByLabel('PT Package', { exact: true })).toHaveValue('package-24')
  await expect(dialog.getByLabel('Weekly frequency', { exact: true })).toHaveValue('2')
  await expect(dialog.getByLabel('Trainer preference', { exact: true })).toHaveValue(seed.clients.find(item => item.id === 'c2').genderPreference)
  await dialog.getByRole('button', { name: 'Continue to Client Availability' }).click()
  await expect(dialog.getByLabel('Client availability blocks')).toContainText('Wednesday')
  await expect(dialog.getByLabel('Client availability blocks')).toContainText('Saturday')
})

test('M4 Marcus retains Amanda through deactivation and reactivation restores retained upcoming sessions', async ({ page }) => {
  await start(page, data => {
    // Retain the empty-plan reactivation regression independently of the fully planned demo.
    Object.assign(data.sessions.find(item => item.id === 's2'), { status: 'not_planned', exercisePlan: [] })
  })
  await page.goto('/#/clients/c1')
  await tab(page, 'Deactivate Client')
  await page.getByRole('dialog', { name: 'Deactivate Amanda Lim?' }).getByRole('button', { name: 'Deactivate Client', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Clients', exact: true })).toBeVisible()
  const frozen = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(frozen.messages.findLast(item => item.clientId === 'c1' && item.recipientRole === 'owner').body).toContain('Package tab')
  await selectDemoIdentity(page, 'u-marcus')
  await page.goto('/#/clients')
  await page.getByLabel('Search client', { exact: true }).fill('Amanda')
  await page.getByRole('button', { name: 'View Amanda Lim', exact: true }).click()
  await expect(page.getByLabel('Client status')).toContainText('Inactive')
  await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0)
  await selectDemoIdentity(page, 'u-owner')
  await page.goto('/#/clients/c1')
  await tab(page, 'Reactivate Client')
  await page.getByRole('dialog', { name: 'Reactivate Amanda Lim?' }).getByRole('button', { name: 'Reactivate Client', exact: true }).click()
  await expect(page.getByLabel('Client status')).toContainText('Active')
  await expect(page.locator('.portal-shell')).toHaveAttribute('aria-busy', 'false')
  const restored = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(restored.sessions).toEqual(frozen.sessions)
  expect(restored.clients.find(item => item.id === 'c1').package.status).toBe('active')
  await selectDemoIdentity(page, 'u-marcus')
  await page.goto('/#/clients')
  await page.getByLabel('Search client', { exact: true }).fill('Amanda')
  await page.getByRole('button', { name: 'View Amanda Lim', exact: true }).click()
  await expect(page.getByLabel('Client status')).toContainText('Active')
  await tab(page, 'Upcoming Sessions')
  await page.getByLabel('Upcoming Sessions').getByRole('button', { name: 'View', exact: true }).first().click()
  await expect(page.getByText('Client inactive', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Package inactive', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Start Plan', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Start Plan', exact: true }).click()
  await page.getByLabel('Exercise 1 name', { exact: true }).click()
  await page.getByRole('button', { name: 'Custom Exercise', exact: true }).click()
  await page.getByLabel('Exercise 1 custom name', { exact: true }).fill('Reactivated session exercise')
  await page.getByRole('button', { name: 'Use Custom Exercise', exact: true }).click()
  await page.locator('.exercise-plan-panel').getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('dialog', { name: 'Save exercise plan?', exact: true }).getByRole('button', { name: 'Save Plan', exact: true }).click()
  await expect(page.getByLabel('Exercise plan', { exact: true })).toContainText('Reactivated session exercise')
  await expect(page.getByRole('button', { name: 'Edit exercise plan', exact: true })).toBeEnabled()
  await page.reload()
  await expect(page.getByLabel('Exercise plan', { exact: true })).toContainText('Reactivated session exercise')
  await expect(page.getByRole('button', { name: 'Edit exercise plan', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Edit exercise plan', exact: true }).click()
  await expect(page.getByLabel('Exercise 1 name', { exact: true })).toContainText('Reactivated session exercise')
})

test('M4 owner edits client and trainer names with confirmation, persistence and unchanged relationships', async ({ page }) => {
  await start(page)
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  for (const [route, field, value, confirmation] of [
    ['clients/c1', 'Client name', 'Amanda Updated', 'Save client information?'],
    ['trainers/t1', 'Trainer name', 'Marcus Updated', 'Save trainer information?'],
  ]) {
    await page.goto(`/#/${route}`)
    const panel = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'General Information', exact: true }) })
    await panel.getByRole('button', { name: 'Edit', exact: true }).click()
    await panel.getByLabel(field, { exact: true }).fill(value)
    await panel.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByRole('dialog', { name: confirmation, exact: true }).getByRole('button', { name: 'Save Changes', exact: true }).click()
    await expect(page.getByRole('heading', { name: value, exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('heading', { name: value, exact: true })).toBeVisible()
  }
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  expect(after.sessions).toEqual(before.sessions)
  expect(after.clients.find(item => item.id === 'c1').trainerId).toBe('t1')
  expect(after.users.find(item => item.id === 'u-marcus').name).toBe('Marcus Updated')
  await selectDemoIdentity(page, 'u-marcus')
  await page.goto('/#/clients')
  await page.getByLabel('Search client', { exact: true }).fill('Amanda Updated')
  await expect(page.getByRole('button', { name: 'View Amanda Updated', exact: true })).toBeVisible()
})

test('M4 calendar day and date are both centred in owner weekly and both roles monthly tiles', async ({ page }) => {
  await start(page)
  for (const [userId, mode] of [['u-owner', 'Weekly'], ['u-owner', 'Monthly'], ['u-marcus', 'Monthly']]) {
    await selectDemoIdentity(page, userId)
    await page.goto('/#/dashboard')
    await page.getByRole('button', { name: mode, exact: true }).click()
    const heads = page.locator('.calendar-day-head')
    await expect(heads.first()).toBeVisible()
    const centres = await heads.evaluateAll(elements => elements.map(element => {
      const day = element.querySelector('span').getBoundingClientRect(), date = element.querySelector('time').getBoundingClientRect(), tile = element.closest('.calendar-day').getBoundingClientRect()
      return [Math.abs(day.x + day.width / 2 - tile.x - tile.width / 2), Math.abs(date.x + date.width / 2 - tile.x - tile.width / 2)]
    }))
    for (const offsets of centres) for (const offset of offsets) expect(offset).toBeLessThanOrEqual(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  }
})

async function reassignableClient(page, conflict = false) {
  await start(page, db => {
    db.sessions = db.sessions.filter(item => item.clientId === 'c1')
    db.trainers.find(item => item.id === 't2').availability = Object.fromEntries(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(day => [day, [['06:00', '23:00']]]))
    const client = db.clients[0], sample = db.sessions.find(item => item.status === 'planned') ?? db.sessions[0]
    client.additionalPackages = [{ ...client.package, id: 'queued', trainerId: 't1', used: 0, startDate: '2027-01-04', endDate: '2027-04-03', fixedWeeklySchedule: client.fixedWeeklySchedule }]
    db.sessions.push({ ...sample, id: 'queued-session', packageId: 'queued', date: '2027-01-04', status: 'planned', acknowledgement: null })
    if (conflict) db.sessions.push({ ...db.sessions.at(-1), id: 'conflicting-booking', clientId: 'c2', trainerId: 't2' })
  })
  await page.goto('/#/clients/c1')
  await page.getByRole('button', { name: 'Reassign Trainer', exact: true }).click()
  return page.getByRole('dialog', { name: 'Permanently Reassign Trainer', exact: true })
}

test('M4 owner permanently reassigns current and additional packages with upcoming bookings and a timestamped history', async ({ page }) => {
  const dialog = await reassignableClient(page)
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  await expect(dialog.getByRole('option', { name: 'Priya Nair — Unavailable', exact: true })).toBeDisabled()
  await dialog.getByLabel('New trainer', { exact: true }).selectOption('t2')
  await dialog.getByRole('button', { name: 'Review Reassignment', exact: true }).click()
  const review = page.getByRole('dialog', { name: 'Reassign trainer for Amanda Lim?', exact: true })
  await expect(review).toContainText('current/additional packages')
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)).toEqual(before)
  await review.getByRole('button', { name: 'Reassign Trainer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByText('Trainer permanently reassigned.', { exact: true })).toBeVisible()
  const after = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY), client = after.clients.find(item => item.id === 'c1')
  expect(client.trainerId).toBe('t2')
  expect(client.package.trainerId).toBe('t2')
  expect(client.additionalPackages[0].trainerId).toBe('t2')
  expect(after.sessions.find(item => item.id === 'queued-session').trainerId).toBe('t2')
  for (const old of before.sessions.filter(item => item.status === 'completed' || item.date < '2026-09-09')) expect(after.sessions.find(item => item.id === old.id)).toEqual(old)
  expect(client.trainerAssignmentHistory).toHaveLength(1)
  expect(client.trainerAssignmentHistory[0].by.id).toBe('u-owner')
  await page.reload()
  const assignment = page.locator('.client-trainer-assignment'), name = assignment.locator('strong')
  const nameBox = await name.boundingBox(), buttonBox = await assignment.getByRole('button', { name: 'Reassign Trainer', exact: true }).boundingBox()
  if (page.viewportSize().width >= 700) {
    const labelBox = await page.locator('.client-trainer-row > span').boundingBox()
    expect(buttonBox.x).toBeGreaterThanOrEqual(labelBox.x + labelBox.width)
    expect(Math.abs(buttonBox.y + buttonBox.height / 2 - labelBox.y - labelBox.height / 2)).toBeLessThanOrEqual(1)
    expect(nameBox.x).toBeGreaterThanOrEqual(buttonBox.x + buttonBox.width)
    expect(buttonBox.x - labelBox.x - labelBox.width).toBeLessThanOrEqual(9)
    const preferenceBox = await page.locator('.info-row').filter({ has: page.getByText('Gender preference', { exact: true }) }).locator('strong').boundingBox()
    expect(Math.abs(nameBox.x + nameBox.width - preferenceBox.x - preferenceBox.width)).toBeLessThanOrEqual(1)
    expect(nameBox.y).toBeGreaterThan(preferenceBox.y + preferenceBox.height)
    expect(Math.abs(nameBox.y + nameBox.height / 2 - labelBox.y - labelBox.height / 2)).toBeLessThanOrEqual(1)
  } else {
    const assignBox = await assignment.boundingBox()
    expect(buttonBox.y).toBeGreaterThanOrEqual(nameBox.y + nameBox.height)
    expect(Math.abs(buttonBox.x + buttonBox.width - assignBox.x - assignBox.width)).toBeLessThanOrEqual(1)
    if (page.viewportSize().width < 700) expect(Math.abs(nameBox.x - assignBox.x)).toBeLessThanOrEqual(1)
  }
  await page.getByRole('button', { name: 'Reassign Trainer', exact: true }).click()
  const history = page.getByLabel('Trainer assignment history', { exact: true })
  await expect(history).toContainText('Marcus Tan')
  await expect(history.locator('time')).toHaveAttribute('dateTime', '2026-09-09T04:00:00.000Z')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('M4 reassignment cancellation and booking conflict retain the draft and leave stored records unchanged', async ({ page }) => {
  const dialog = await reassignableClient(page, true)
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)
  await dialog.getByLabel('New trainer', { exact: true }).selectOption('t2')
  await dialog.getByRole('button', { name: 'Review Reassignment', exact: true }).click()
  let review = page.getByRole('dialog', { name: 'Reassign trainer for Amanda Lim?', exact: true })
  await review.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog.getByLabel('New trainer', { exact: true })).toHaveValue('t2')
  await dialog.getByRole('button', { name: 'Review Reassignment', exact: true }).click()
  review = page.getByRole('dialog', { name: 'Reassign trainer for Amanda Lim?', exact: true })
  await review.getByRole('button', { name: 'Reassign Trainer', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('booking conflict')
  await expect(dialog.getByLabel('New trainer', { exact: true })).toHaveValue('t2')
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), KEY)).toEqual(before)
})

test('M4 permanent reassignment is hidden from trainers and inactive client profiles', async ({ page }) => {
  await start(page, db => { db.clients[1].status = 'inactive' })
  await page.goto('/#/clients/c2')
  await expect(page.getByLabel('Client status')).toContainText('Inactive')
  await expect(page.getByRole('button', { name: 'Reassign Trainer', exact: true })).toHaveCount(0)
  await selectDemoIdentity(page, 'u-marcus')
  await page.goto('/#/clients/c1')
  await expect(page.getByRole('heading', { name: 'Amanda Lim', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reassign Trainer', exact: true })).toHaveCount(0)
})
