import { test, expect, drawClientSignature, selectDemoIdentity } from './fixtures.js'
import { seed } from '../src/data/seed.js'
import { withBusyCalendar } from '../src/test/fixtures/calendar.js'
const database='fitfinity-m2-demo-db-v4'
const stored=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),database)
async function changeRoute(page,path) { await page.evaluate(value=>{location.hash=`#/${value}`},path) }
const calendarDay = (page, date) => page.locator(`.calendar-day[data-date="${date}"]`)
async function expectCalendarDates(page, dates) {
  await expect(page.locator('.calendar-day')).toHaveCount(dates.length)
  expect(await page.locator('.calendar-day').evaluateAll(days => days.map(day => day.dataset.date))).toEqual(dates)
}
async function expectCalendarHeaderLayout(page) {
  await expect(page.getByLabel('Calendar date')).toHaveCount(0)
  await expect(page.locator('.calendar-header input[type="date"]')).toHaveCount(0)
  const modes = await page.getByLabel('Calendar view').boundingBox()
  const title = await page.getByRole('heading', { name: 'Calendar', exact: true }).boundingBox()
  const header = await page.locator('.calendar-header').boundingBox()
  expect(modes.x).toBeGreaterThanOrEqual(title.x + title.width)
  expect(Math.abs(modes.y + modes.height / 2 - title.y - title.height / 2)).toBeLessThanOrEqual(1)
  expect(Math.abs(modes.x + modes.width - header.x - header.width)).toBeLessThanOrEqual(1)
  for (const button of await page.getByLabel('Calendar view').getByRole('button').all()) {
    expect((await button.boundingBox()).height).toBeGreaterThanOrEqual(44)
  }
  const toolbar = page.locator('.calendar-toolbar')
  const previous = await toolbar.getByRole('button', { name: 'Previous calendar period' }).boundingBox()
  const next = await toolbar.getByRole('button', { name: 'Next calendar period' }).boundingBox()
  const heading = await toolbar.locator('.calendar-range').boundingBox()
  expect(heading.x).toBeGreaterThanOrEqual(previous.x + previous.width)
  expect(heading.x + heading.width).toBeLessThanOrEqual(next.x)
  expect(previous.y).toBeGreaterThanOrEqual(modes.y + modes.height)
  expect(next.y).toBeGreaterThanOrEqual(modes.y + modes.height)
}

test('M4 weekly and monthly calendars support periods, session navigation and retained Back state',async({page})=>{
  await page.clock.setFixedTime(new Date('2026-12-30T04:00:00Z'))
  await page.addInitScript(data => { const key = 'fitfinity-m2-demo-db-v4'; if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, seed)
  await page.goto('/#/dashboard')
  await expect(page.getByRole('button', { name: 'Weekly', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('Calendar date')).toHaveCount(0)
  const initialWeek = ['2026-12-30', '2026-12-31', '2027-01-01', '2027-01-02', '2027-01-03', '2027-01-04', '2027-01-05']
  await expectCalendarDates(page, initialWeek)
  await expect(page.locator('.calendar-day-head > span')).toHaveText(['Today', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue'])
  await expect(page.locator('.calendar-range option:checked')).toHaveText(/30 Dec 2026 – 05 Jan 2027/)
  await expect(page.getByRole('button', { name: 'Next calendar period' })).toBeDisabled()
  await expect(page.getByLabel('Calendar week').locator('option:not([hidden])')).toHaveCount(5)
  await page.getByLabel('Calendar week').selectOption('2026-12-22')
  await expectCalendarDates(page, ['2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25', '2026-12-26', '2026-12-27', '2026-12-28'])
  await page.reload()
  await expect(page.getByLabel('Calendar week')).toHaveValue('2026-12-22')
  await page.getByRole('button',{name:'Monthly',exact:true}).click()
  await expect(page.getByLabel('Calendar date')).toHaveCount(0)
  await expectCalendarDates(page, Array.from({ length: 31 }, (_, index) => `2026-12-${String(index + 1).padStart(2, '0')}`))
  await expect(page.getByLabel('Calendar month').locator('option')).toHaveCount(12)
  await page.getByLabel('Calendar month').selectOption('2026-01-01')
  await expect(page.getByRole('button', { name: 'Previous calendar period' })).toBeDisabled()
  await page.getByLabel('Calendar month').selectOption('2026-09-01')
  await expectCalendarDates(page, Array.from({ length: 30 }, (_, index) => `2026-09-${String(index + 1).padStart(2, '0')}`))
  await expect(page.locator('.calendar-range option:checked')).toHaveText(/Sept? 2026/)
  await expect(page.locator('.calendar-day.calendar-adjacent')).toHaveCount(0)
  await expect(page.getByLabel('Selected day sessions')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Today', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Show sessions for 2026-09-07', exact: true }).click()
  const day = page.getByRole('dialog', { name: 'Calendar sessions' })
  await expect(day).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('position', 'fixed')
  await day.getByRole('button').filter({hasText:'Amanda Lim'}).first().click()
  await expect(page.getByRole('button',{name:'Client Signature',exact:true})).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button',{name:'Monthly',exact:true})).toHaveAttribute('aria-pressed','true')
  await expectCalendarDates(page, Array.from({ length: 30 }, (_, index) => `2026-09-${String(index + 1).padStart(2, '0')}`))
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Next calendar period'}).click()
  await expectCalendarDates(page, Array.from({ length: 31 }, (_, index) => `2026-10-${String(index + 1).padStart(2, '0')}`))
  await expect(page.locator('.calendar-range option:checked')).toHaveText('Oct 2026')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
})
test('M4 client signing requires ink, clears, confirms once and reopens after refresh',async({page})=>{
  await page.clock.setFixedTime(new Date('2026-09-07T04:00:00Z'))
  await page.addInitScript(data => { const key = 'fitfinity-m2-demo-db-v4'; if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, seed)
  await page.goto('/#/sessions/s1')
  await page.getByRole('button',{name:'Client Signature',exact:true}).click()
  await expect(page.getByRole('button',{name:'Review Completion'})).toBeDisabled()
  await drawClientSignature(page)
  await page.getByRole('button',{name:'Clear Signature'}).click()
  await expect(page.getByRole('button',{name:'Review Completion'})).toBeDisabled()
  await drawClientSignature(page)
  await page.getByRole('button',{name:'Review Completion'}).click()
  const review=page.getByRole('dialog',{name:'Complete this session?'})
  await expect(review.getByRole('img')).toBeVisible()
  await review.getByRole('button',{name:'Complete Session'}).click()
  await expect(page.getByRole('button',{name:'View Client Signature'})).toBeVisible()
  const saved = (await stored(page)).sessions.find(item => item.id === 's1')
  await page.reload()
  await page.getByRole('button',{name:'View Client Signature'}).click()
  const preview = page.getByRole('dialog',{name:'Client signature'})
  await expect(preview.getByRole('img')).toBeVisible()
  await expect(preview).toContainText('Signed on')
  await expect(preview.locator('time')).toHaveAttribute('datetime', saved.acknowledgement.recordedAt)
  await expect(preview.getByRole('textbox')).toHaveCount(0)
  await expect(preview.getByRole('button', { name: 'Clear Signature' })).toHaveCount(0)
  await expect(preview.getByRole('button', { name: 'Review Completion' })).toHaveCount(0)
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Update Completion' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Correct to Client Signature' })).toHaveCount(0)
  await expect(page.getByLabel('Acknowledgement history').locator('time')).toHaveAttribute('datetime', saved.acknowledgement.recordedAt)
  expect((await stored(page)).sessions.find(item => item.id === 's1')).toEqual(saved)
  expect((await stored(page)).packageCreditTransactions.filter(item=>item.sessionId==='s1')).toHaveLength(1)
})
test('M4 content preview, save, filtering, edit and archive persist',async({page})=>{
  await page.goto('/#/content/new')
  await page.getByLabel('Content title').fill('Studio introduction')
  await page.getByLabel('Content key').fill('studio/intro')
  await page.getByLabel('Content body').fill('Welcome to our studio.')
  await page.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Content preview'})).toContainText('Welcome to our studio.')
  await page.getByRole('button',{name:'Close Preview'}).click()
  await page.getByRole('button',{name:'Save Content',exact:true}).click()
  await page.getByRole('dialog',{name:'Save content?'}).getByRole('button',{name:'Save Content'}).click()
  await expect(page).toHaveURL(/#\/content\/content-/)
  await page.reload()
  await page.getByLabel('Content status').selectOption('archived')
  await page.getByRole('button',{name:'Save Content',exact:true}).click()
  await page.getByRole('dialog',{name:'Save content?'}).getByRole('button',{name:'Save Content'}).click()
  await expect(page.getByRole('button',{name:'Back to Content'})).toBeVisible()
  await page.getByRole('button',{name:'Back to Content'}).click()
  await page.getByLabel('Search content').fill('introduction')
  await page.getByLabel('Filter content status').selectOption('archived')
  await expect(page.getByRole('button',{name:'Edit Studio introduction'})).toBeVisible()
})
test('M4 signed-in trainers cannot resolve another client or session through a direct URL',async({page})=>{
  await page.goto('/#/dashboard')
  await selectDemoIdentity(page, 'u-marcus')
  await expect(page.getByRole('heading',{name:'Trainer Dashboard'})).toBeVisible()
  await changeRoute(page,'clients/c2')
  await expect(page.getByText('This client is unavailable for your account.')).toBeVisible()
  await changeRoute(page,'content')
  await expect(page.getByRole('heading',{name:'Page unavailable'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Add Content'})).toHaveCount(0)
})
test('M4 blocked WhatsApp popup exposes a retry link without reporting delivery',async({page})=>{
  await page.clock.setFixedTime(new Date('2026-09-07T04:00:00Z'))
  await page.addInitScript(data => { const key = 'fitfinity-m2-demo-db-v4'; if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, seed)
  await page.goto('/#/sessions/s1')
  await page.evaluate(()=>{window.open=()=>null})
  await page.getByRole('button',{name:'Export Summary',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Export Summary'})
  await dialog.getByRole('button',{name:'Continue to WhatsApp'}).click()
  await expect(page.getByRole('link',{name:'Open summary in WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa.me\//)
  const data=await stored(page)
  expect(data?.sessions.find(item=>item.id==='s1').whatsappOpenedAt).toBeFalsy()
})

test.describe('M4 signed-out account flows',()=>{
  test.use({demoSignedIn:false})
  test('M4 sign-in, password replacement, sign-out and old-password rejection work end to end',async({page})=>{
    await page.goto('/#/dashboard')
    await page.getByLabel('Account',{exact:true}).selectOption('u-owner')
    await page.getByLabel('Password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Calendar'})).toBeVisible()
    await changeRoute(page,'change-password')
    await page.getByLabel('Current password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button', { name: 'Password requirements', exact: true }).click()
    await expect(page.locator('.notification-region [role="status"]')).toContainText('12–128 characters')
    await expect(page.locator('.account-form .helper')).toHaveCount(0)
    await page.getByLabel('New password',{exact:true}).fill('short')
    await page.getByLabel('Confirm new password',{exact:true}).fill('short')
    await page.getByRole('button',{name:'Save Password'}).click()
    await expect(page.locator('.notification-region [role="alert"]')).toContainText('12–128 characters')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByLabel('New password',{exact:true})).toHaveValue('short')
    await page.getByLabel('New password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByLabel('Confirm new password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByRole('button',{name:'Save Password'}).click()
    await page.getByRole('dialog',{name:'Change password?'}).getByRole('button',{name:'Change Password'}).click()
    await expect(page.getByLabel('Current password',{exact:true})).toHaveValue('')
    await page.getByRole('button',{name:'Open profile menu'}).click()
    await page.getByRole('menuitem',{name:'Sign Out'}).click()
    await expect(page).toHaveURL(/#\/dashboard$/)
    await expect(page.locator('.portal-shell')).toHaveCount(0)
    await page.getByLabel('Account',{exact:true}).selectOption('u-owner')
    await page.getByLabel('Password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('alert')).toContainText('incorrect')
    await page.getByLabel('Password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Calendar'})).toBeVisible()
    await expect(page).toHaveURL(/#\/dashboard$/)
  })
  test('M4 expired sessions return to sign-in after reload',async({page})=>{
    await page.addInitScript(()=>localStorage.setItem('fitfinity-demo-session-v1',JSON.stringify({userId:'u-owner',expiresAt:1})))
    await page.goto('/#/clients/c1')
    await expect(page.getByRole('heading',{name:'Sign in'})).toBeVisible()
    await expect(page.getByText('Amanda Lim',{exact:true})).toHaveCount(0)
  })
})

test('M4 Oracle calendars show owner counts, every trainer weekly row and grouped complete day popups', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-02T15:59:00Z'))
  const data = withBusyCalendar(seed)
  for (const session of data.sessions) session.status = ['not_planned', 'planned', 'completed'][(Number(session.from.slice(0, 2)) - 8) % 3]
  const statusLabels = ['Not Planned', 'Planned', 'Completed', 'Not Planned', 'Planned', 'Completed', 'Not Planned', 'Planned']
  data.sessions.push({ ...data.sessions[0], id: 'single-session', date: '2026-09-05', trainerId: 't1' })
  await page.addInitScript(({ key, data }) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data))
  }, { key: database, data })
  await page.goto('/#/dashboard')
  await expect(page.getByRole('heading', { name: 'Calendar', exact: true })).toBeVisible()
  for (const [identity, total] of [['u-owner', 14], ['u-marcus', 8]]) {
    if (identity === 'u-marcus') {
      await page.clock.setFixedTime(new Date('2026-09-02T15:59:00Z'))
      await page.reload()
      await selectDemoIdentity(page, identity)
    }
    await page.getByRole('button', { name: 'Next calendar period' }).click()
    await page.getByRole('button', { name: 'Previous calendar period' }).click()
    // Cross Singapore midnight after navigation has retained the selected week.
    await page.clock.setFixedTime(new Date('2026-09-02T16:01:00Z'))
    await page.reload()
    await expectCalendarDates(page, ['2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'])
    for (const mode of ['Weekly', 'Monthly']) {
      await page.getByRole('button', { name: mode, exact: true }).click()
      await expect(page.getByLabel('Calendar date')).toHaveCount(0)
      if (mode === 'Weekly') {
        await expectCalendarDates(page, ['2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'])
        if (identity === 'u-owner') await expect(page.locator('.calendar-day-head > span')).toHaveText(['Wed', 'Today', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue'])
        else {
          await expect(calendarDay(page, '2026-09-02').locator('.calendar-agenda-date')).toContainText(/Wednesday, 02 Sept? 2026/)
          await expect(calendarDay(page, '2026-09-08').locator('.calendar-agenda-date')).toContainText(/Tuesday, 08 Sept? 2026/)
        }
      } else await expectCalendarDates(page, Array.from({ length: 30 }, (_, index) => `2026-09-${String(index + 1).padStart(2, '0')}`))
      const date = page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true })
      const busy = page.locator('.calendar-day').filter({ has: date })
      const trainerWeek = identity === 'u-marcus' && mode === 'Weekly'
      await expect(date).toHaveAttribute('aria-haspopup', 'dialog')
      await expect(date.locator('.calendar-date-action')).toBeVisible()
      await expect(date.locator('.calendar-date-action')).toContainText('View day')
      expect((await date.boundingBox()).height).toBeGreaterThanOrEqual(44)
      await expect(page.locator('.calendar-more')).toHaveCount(0)
      if (trainerWeek) {
        await expect(busy.locator('.calendar-event strong')).toHaveText(['08:00–09:00', '09:00–10:00', '10:00–11:00', '11:00–12:00', '12:00–13:00', '13:00–14:00', '14:00–15:00', '15:00–16:00'])
        await expect(busy.locator('.calendar-event-status')).toHaveText(statusLabels)
        const rows = busy.locator('.calendar-event')
        for (const row of await rows.all()) {
          await expect(row).toBeVisible()
          const time = await row.locator('strong').boundingBox()
          const client = await row.locator('.calendar-event-client').boundingBox()
          const status = row.locator('.calendar-event-status')
          const badge = await status.boundingBox()
          expect(Math.abs(time.y + time.height / 2 - client.y - client.height / 2)).toBeLessThanOrEqual(1)
          expect(client.x).toBeGreaterThanOrEqual(time.x + time.width)
          expect(Math.abs(time.y + time.height / 2 - badge.y - badge.height / 2)).toBeLessThanOrEqual(1)
          expect(badge.x).toBeGreaterThanOrEqual(client.x + client.width)
          expect(await status.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(0)
          await expect(row).toHaveAccessibleName(new RegExp(`, ${await status.innerText()}$`))
        }
        await rows.last().click()
        await expect(page).toHaveURL(/#\/sessions\/busy-7$/)
        await expect(page.getByRole('button', { name: 'Client Signature', exact: true })).toBeVisible()
        await page.goBack()
        await expect(page.getByRole('button', { name: 'Weekly', exact: true })).toHaveAttribute('aria-pressed', 'true')
        await expectCalendarDates(page, ['2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'])
      } else {
        await expect(date.locator('strong')).toHaveText(String(total))
        await expect(date.locator('.calendar-count-label')).toHaveText('sessions')
        const single = page.getByRole('button', { name: 'Show sessions for 2026-09-05', exact: true })
        await expect(single.locator('.calendar-count-label')).toHaveText('session')
        await expect(page.locator('.calendar-grid .calendar-event')).toHaveCount(0)
        const layout = await page.locator('.calendar-grid').evaluate(grid => {
          const cells = [...grid.children].slice(0, 7).map(cell => cell.getBoundingClientRect())
          const bounds = grid.getBoundingClientRect()
          return { top: cells.map(cell => cell.top), left: cells.map(cell => cell.left), right: Math.max(...cells.map(cell => cell.right)), cellWidth: cells[0].width, gridLeft: bounds.left, width: innerWidth }
        })
        if (mode === 'Monthly') {
          expect(Math.max(...layout.top.slice(0, 6)) - Math.min(...layout.top.slice(0, 6))).toBeLessThanOrEqual(1)
          expect(layout.top[6]).toBeGreaterThan(layout.top[0])
          expect(Math.abs(layout.left[0] - layout.gridLeft - layout.cellWidth - 1)).toBeLessThanOrEqual(1)
          expect(Math.abs(layout.left[6] - layout.gridLeft - 1)).toBeLessThanOrEqual(1)
        } else expect(Math.max(...layout.top) - Math.min(...layout.top)).toBeLessThanOrEqual(1)
        expect(Math.min(...layout.left)).toBeGreaterThanOrEqual(0)
        expect(layout.right).toBeLessThanOrEqual(layout.width)
      }
      const emptyDate = page.getByRole('button', { name: 'Show sessions for 2026-09-04', exact: true })
      const emptyDay = calendarDay(page, '2026-09-04')
      await expect(emptyDate).toHaveCount(0)
      await expect(emptyDay.locator('button, [tabindex], .calendar-date-action, .calendar-count-label')).toHaveCount(0)
      await expect(emptyDay).not.toContainText('View day')
      if (trainerWeek) {
        await expect(emptyDay.locator('.calendar-agenda-date')).toContainText(/Friday, 04 Sept? 2026/)
        await expect(emptyDay.locator('.calendar-agenda-date')).not.toHaveAttribute('aria-haspopup')
        await expect(emptyDay).toContainText('No sessions')
      } else {
        await expect(emptyDay.locator('.calendar-day-head time')).toHaveText('4')
        await expect(emptyDay).not.toContainText('No sessions')
        if (mode === 'Monthly') expect((await emptyDay.boundingBox()).height).toBeGreaterThanOrEqual(76)
      }
      // Restore neutral focus/hover after session Back before measuring past-day dimming.
      await page.getByRole('button', { name: mode, exact: true }).focus()
      await page.mouse.move(0, 0)
      const today = calendarDay(page, '2026-09-03')
      const future = emptyDay
      await expect(busy).toHaveClass(/calendar-past/)
      await expect(date).toBeEnabled()
      await expect(today).not.toHaveClass(/calendar-past/)
      await expect(today).toHaveClass(/calendar-today/)
      await expect(today).toHaveAttribute('aria-current', 'date')
      await expect(today.getByText('Today', { exact: true })).toBeVisible()
      expect(await today.evaluate(day => getComputedStyle(day).boxShadow)).not.toBe('none')
      await expect(future).not.toHaveClass(/calendar-past/)
      await expect(today).toHaveCSS('opacity', '1')
      await expect(future).toHaveCSS('opacity', '1')
      const pastOpacity = await busy.evaluate(day => Number(getComputedStyle(day).opacity))
      expect(pastOpacity).toBeGreaterThan(0)
      expect(pastOpacity).toBeLessThan(1)
      for (const surface of [busy, today]) {
        const ratios = await surface.evaluate(day => {
          const rgba = value => value.match(/[\d.]+/g).map(Number)
          const background = element => {
            if (!element) return [255, 255, 255]
            const [r, g, b, a = 1] = rgba(getComputedStyle(element).backgroundColor)
            if (a === 1) return [r, g, b]
            const behind = background(element.parentElement)
            return [r, g, b].map((value, index) => value * a + behind[index] * (1 - a))
          }
          const luminance = rgb => {
            const channels = rgb.slice(0, 3).map(value => {
              const channel = value / 255
              return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4
            })
            return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722
          }
          // CSS opacity composites the entire day onto the grid's background.
          const opacity = Number(getComputedStyle(day).opacity)
          const behind = background(day.parentElement)
          const dim = rgb => rgb.slice(0, 3).map((value, index) => value * opacity + behind[index] * (1 - opacity))
          return [...day.querySelectorAll('.calendar-date strong, .calendar-count-label, .calendar-date-action, .calendar-day-head, .calendar-today-label, .calendar-agenda-date, .calendar-event strong, .calendar-event-client, .calendar-event-status')].map(element => {
            const foreground = luminance(dim(rgba(getComputedStyle(element).color)))
            const surface = luminance(dim(background(element)))
            return (Math.max(foreground, surface) + 0.05) / (Math.min(foreground, surface) + 0.05)
          })
        })
        expect(Math.min(...ratios)).toBeGreaterThanOrEqual(4.5)
      }
      await date.focus()
      await expect(busy).toHaveCSS('opacity', '1')
      await date.click()
      const dialog = page.getByRole('dialog', { name: 'Calendar sessions' })
      await expect(dialog).toHaveCSS('opacity', '1')
      await expect(dialog.locator('.calendar-event')).toHaveCount(total)
      if (identity === 'u-owner') {
        const groups = dialog.locator('.calendar-trainer-group')
        await expect(groups).toHaveCount(2)
        await expect(groups.nth(0).getByRole('heading')).toHaveText(seed.trainers.find(trainer => trainer.id === 't1').name)
        await expect(groups.nth(0).locator('.calendar-event')).toHaveCount(8)
        await expect(groups.nth(1).locator('.calendar-event')).toHaveCount(6)
        await expect(groups.nth(0).locator('.calendar-event-status')).toHaveText(statusLabels)
        await expect(groups.nth(1).locator('.calendar-event-status')).toHaveText(statusLabels.slice(0, 6))
      } else {
        await expect(dialog.locator('.calendar-trainer-group')).toHaveCount(0)
        await expect(dialog.locator('.calendar-event-status')).toHaveText(statusLabels)
        await expect(dialog.locator('.calendar-event').last()).toContainText('15:00–16:00')
      }
      for (const row of await dialog.locator('.calendar-event').all()) {
        const status = row.locator('.calendar-event-status')
        await expect(status).toBeVisible()
        await expect(row).toHaveAccessibleName(new RegExp(`, ${await status.innerText()}$`))
      }
      await page.getByRole('button', { name: 'Close calendar sessions' }).click()
      await expect(dialog).toHaveCount(0)
    }
  }
  await page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true }).click()
  await page.getByRole('dialog', { name: 'Calendar sessions' }).locator('.calendar-event').last().click()
  await expect(page).toHaveURL(/#\/sessions\/busy-7$/)
  await expect(page.getByRole('button', { name: 'Client Signature', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Monthly', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expectCalendarDates(page, Array.from({ length: 30 }, (_, index) => `2026-09-${String(index + 1).padStart(2, '0')}`))
  const original = page.viewportSize()
  for (const width of [320, 900, original.width]) {
    await page.setViewportSize({ ...original, width })
    const todayHead = page.locator('.calendar-today .calendar-day-head')
    await expect(todayHead.getByText('Today', { exact: true })).toBeVisible()
    expect(await todayHead.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(0)
    await expectCalendarHeaderLayout(page)
    const count = page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true })
    await expect(count.locator('strong')).toHaveText('8')
    await expect(count.locator('.calendar-count-label')).toBeVisible()
    await expect(count.locator('.calendar-date-action')).toBeVisible()
    await expect(page.locator('.calendar-grid .calendar-event')).toHaveCount(0)
    const emptyMonthDay = calendarDay(page, '2026-09-04')
    await expect(emptyMonthDay.locator('button, [tabindex], .calendar-date-action, .calendar-count-label')).toHaveCount(0)
    await expect(emptyMonthDay.locator('time')).toHaveText('4')
    await page.getByRole('button', { name: 'Weekly', exact: true }).click()
    await expectCalendarDates(page, ['2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'])
    await expectCalendarHeaderLayout(page)
    const busy = page.locator('.calendar-day').filter({ has: page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true }) })
    await expect(busy.locator('.calendar-event')).toHaveCount(8)
    await expect(busy.locator('.calendar-event-status')).toHaveText(statusLabels)
    for (const status of await busy.locator('.calendar-event-status').all()) {
      await expect(status).toBeVisible()
      expect(await status.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(0)
    }
    await expect(busy.locator('.calendar-event').last()).toBeVisible()
    const emptyWeekDay = calendarDay(page, '2026-09-04')
    await expect(emptyWeekDay.locator('button, [tabindex], .calendar-date-action')).toHaveCount(0)
    await expect(emptyWeekDay).toContainText('No sessions')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0)
    await page.getByRole('button', { name: 'Monthly', exact: true }).click()
  }
})

test('M4 calendar date popup closes with browser Back and reopens an empty day without restoring a daily dashboard', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2032-02-29T04:00:00Z'))
  await page.addInitScript(data => { const key = 'fitfinity-m2-demo-db-v4'; if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data)) }, seed)
  await page.goto('/#/dashboard')
  await page.getByRole('button', { name: 'Monthly', exact: true }).click()
  await expect(page.getByLabel('Calendar date')).toHaveCount(0)
  await expectCalendarDates(page, Array.from({ length: 29 }, (_, index) => `2032-02-${String(index + 1).padStart(2, '0')}`))
  const emptyToday = calendarDay(page, '2032-02-29')
  await expect(emptyToday).toHaveAttribute('aria-current', 'date')
  await expect(emptyToday.getByText('Today', { exact: true })).toBeVisible()
  await expect(emptyToday.locator('time')).toHaveText('29')
  await expect(page.getByLabel('Monthly calendar').locator('button, [tabindex], .calendar-date-action, .calendar-count-label')).toHaveCount(0)
  await page.getByRole('button', { name: 'Weekly', exact: true }).click()
  await expectCalendarDates(page, ['2032-02-29', '2032-03-01', '2032-03-02', '2032-03-03', '2032-03-04', '2032-03-05', '2032-03-06'])
  await expect(page.getByLabel('Calendar date')).toHaveCount(0)
  await expect(page.getByLabel('Weekly calendar').locator('button, [tabindex], .calendar-date-action, .calendar-count-label')).toHaveCount(0)
  await expect(emptyToday.locator('.calendar-day-head time')).toHaveText('29')
  await expect(emptyToday).not.toContainText('View day')
  // A saved day URL still opens an informative dialog when that day has no records.
  await changeRoute(page, 'dashboard/day/2032-02-29')
  await expect(page.getByRole('dialog', { name: 'Calendar sessions' })).toContainText('No sessions for this day.')
  await page.goBack()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expectCalendarDates(page, ['2032-02-29', '2032-03-01', '2032-03-02', '2032-03-03', '2032-03-04', '2032-03-05', '2032-03-06'])
  await expect(page.getByRole('button', { name: 'Weekly', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.goForward()
  await expect(page.getByRole('dialog', { name: 'Calendar sessions' })).toBeVisible()
  await page.getByRole('button', { name: 'Close calendar sessions' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Selected day sessions')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Today', exact: true })).toHaveCount(0)
})
