import { test, expect, drawClientSignature, selectDemoIdentity } from './fixtures.js'
import { seed } from '../src/data/seed.js'
import { withBusyCalendar } from '../src/test/fixtures/calendar.js'
const database='fitfinity-m2-demo-db-v4'
const stored=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),database)
async function changeRoute(page,path) { await page.evaluate(value=>{location.hash=`#/${value}`},path) }

test('M4 weekly and monthly calendars support periods, session navigation and retained Back state',async({page})=>{
  await page.goto('/#/dashboard')
  await page.getByRole('button',{name:'Monthly',exact:true}).click()
  await page.getByLabel('Calendar date').fill('2026-09-02')
  await expect(page.locator('.calendar-day')).toHaveCount(42)
  await expect(page.getByLabel('Selected day sessions')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Today', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true }).click()
  const day = page.getByRole('dialog', { name: 'Calendar sessions' })
  await expect(day).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('position', 'fixed')
  await day.getByRole('button').filter({hasText:'Amanda Lim'}).first().click()
  await expect(page.getByRole('button',{name:'Client Signature',exact:true})).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button',{name:'Monthly',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByLabel('Calendar date')).toHaveValue('2026-09-02')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Next calendar period'}).click()
  await expect(page.getByLabel('Calendar date')).toHaveValue('2026-10-01')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
})
test('M4 client signing requires ink, clears, confirms once and reopens after refresh',async({page})=>{
  await page.goto('/#/sessions/s1')
  await page.getByRole('button',{name:'Client Signature',exact:true}).click()
  await expect(page.getByRole('button',{name:'Review Completion'})).toBeDisabled()
  await drawClientSignature(page)
  await page.getByRole('button',{name:'Clear Signature'}).click()
  await expect(page.getByRole('button',{name:'Review Completion'})).toBeDisabled()
  await drawClientSignature(page)
  await page.getByRole('button',{name:'Review Completion'}).click()
  const review=page.getByRole('dialog',{name:'Complete this session?'})
  await expect(review.getByRole('img')).toBeVisible()
  await review.getByRole('button',{name:'Complete Session'}).click()
  await expect(page.getByRole('button',{name:'View Client Signature'})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'View Client Signature'}).click()
  await expect(page.getByRole('dialog',{name:'Client signature'}).getByRole('img')).toBeVisible()
  expect((await stored(page)).packageCreditTransactions.filter(item=>item.sessionId==='s1')).toHaveLength(1)
})
test('M4 content preview, save, filtering, edit and archive persist',async({page})=>{
  await page.goto('/#/content/new')
  await page.getByLabel('Content title').fill('Studio introduction')
  await page.getByLabel('Content key').fill('studio/intro')
  await page.getByLabel('Content body').fill('Welcome to our studio.')
  await page.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Content preview'})).toContainText('Welcome to our studio.')
  await page.getByRole('button',{name:'Close Preview'}).click()
  await page.getByRole('button',{name:'Save Content',exact:true}).click()
  await page.getByRole('dialog',{name:'Save content?'}).getByRole('button',{name:'Save Content'}).click()
  await expect(page).toHaveURL(/#\/content\/content-/)
  await page.reload()
  await page.getByLabel('Content status').selectOption('archived')
  await page.getByRole('button',{name:'Save Content',exact:true}).click()
  await page.getByRole('dialog',{name:'Save content?'}).getByRole('button',{name:'Save Content'}).click()
  await expect(page.getByRole('button',{name:'Back to Content'})).toBeVisible()
  await page.getByRole('button',{name:'Back to Content'}).click()
  await page.getByLabel('Search content').fill('introduction')
  await page.getByLabel('Filter content status').selectOption('archived')
  await expect(page.getByRole('button',{name:'Edit Studio introduction'})).toBeVisible()
})
test('M4 signed-in trainers cannot resolve another client or session through a direct URL',async({page})=>{
  await page.goto('/#/dashboard')
  await selectDemoIdentity(page, 'u-marcus')
  await expect(page.getByRole('heading',{name:'Trainer Dashboard'})).toBeVisible()
  await changeRoute(page,'clients/c2')
  await expect(page.getByText('This client is unavailable for your account.')).toBeVisible()
  await changeRoute(page,'content')
  await expect(page.getByRole('heading',{name:'Page unavailable'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Add Content'})).toHaveCount(0)
})
test('M4 blocked WhatsApp popup exposes a retry link without reporting delivery',async({page})=>{
  await page.goto('/#/sessions/s1')
  await page.evaluate(()=>{window.open=()=>null})
  await page.getByRole('button',{name:'Export Summary',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Export Summary'})
  await dialog.getByRole('button',{name:'Continue to WhatsApp'}).click()
  await expect(page.getByRole('link',{name:'Open summary in WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa.me\//)
  const data=await stored(page)
  expect(data?.sessions.find(item=>item.id==='s1').whatsappOpenedAt).toBeFalsy()
})

test.describe('M4 signed-out account flows',()=>{
  test.use({demoSignedIn:false})
  test('M4 sign-in, password replacement, sign-out and old-password rejection work end to end',async({page})=>{
    await page.goto('/#/dashboard')
    await page.getByLabel('Account',{exact:true}).selectOption('u-owner')
    await page.getByLabel('Password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Calendar'})).toBeVisible()
    await changeRoute(page,'change-password')
    await page.getByLabel('Current password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button', { name: 'Password requirements', exact: true }).click()
    await expect(page.locator('.notification-region [role="status"]')).toContainText('12–128 characters')
    await expect(page.locator('.account-form .helper')).toHaveCount(0)
    await page.getByLabel('New password',{exact:true}).fill('short')
    await page.getByLabel('Confirm new password',{exact:true}).fill('short')
    await page.getByRole('button',{name:'Save Password'}).click()
    await expect(page.locator('.notification-region [role="alert"]')).toContainText('12–128 characters')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByLabel('New password',{exact:true})).toHaveValue('short')
    await page.getByLabel('New password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByLabel('Confirm new password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByRole('button',{name:'Save Password'}).click()
    await page.getByRole('dialog',{name:'Change password?'}).getByRole('button',{name:'Change Password'}).click()
    await expect(page.getByLabel('Current password',{exact:true})).toHaveValue('')
    await page.getByRole('button',{name:'Open profile menu'}).click()
    await page.getByRole('menuitem',{name:'Sign Out'}).click()
    await page.getByLabel('Account',{exact:true}).selectOption('u-owner')
    await page.getByLabel('Password',{exact:true}).fill('FitfinityDemo1!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('alert')).toContainText('incorrect')
    await page.getByLabel('Password',{exact:true}).fill('NewDemoPassword42!')
    await page.getByRole('button',{name:'Sign In',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Calendar'})).toBeVisible()
  })
  test('M4 expired sessions return to sign-in after reload',async({page})=>{
    await page.addInitScript(()=>localStorage.setItem('fitfinity-demo-session-v1',JSON.stringify({userId:'u-owner',expiresAt:1})))
    await page.goto('/#/clients/c1')
    await expect(page.getByRole('heading',{name:'Sign in'})).toBeVisible()
    await expect(page.getByText('Amanda Lim',{exact:true})).toHaveCount(0)
  })
})

test('M4 calendars show five scoped previews and a visible overflow action opens every session', async ({ page }) => {
  await page.addInitScript(({ key, data }) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(data))
  }, { key: database, data: withBusyCalendar(seed) })
  await page.goto('/#/dashboard')
  await page.getByLabel('Calendar date').fill('2026-09-02')
  await expect(page.getByRole('button', { name: 'Show 9 more sessions for 2026-09-02' })).toHaveText('+9 more')
  await selectDemoIdentity(page, 'u-marcus')
  await page.getByLabel('Calendar date').fill('2026-09-02')
  for (const mode of ['Weekly', 'Monthly']) {
    await page.getByRole('button', { name: mode, exact: true }).click()
    const date = page.getByRole('button', { name: 'Show sessions for 2026-09-02', exact: true })
    const busy = page.locator('.calendar-day').filter({ has: date })
    await expect(date.locator('.calendar-date-action')).toBeVisible()
    await expect(date).toHaveAttribute('aria-haspopup', 'dialog')
    await expect(date).toContainText('8 sessions')
    expect((await date.boundingBox()).height).toBeGreaterThanOrEqual(44)
    await expect(busy.locator('.calendar-event strong')).toHaveText(['08:00–09:00', '09:00–10:00', '10:00–11:00', '11:00–12:00', '12:00–13:00'])
    const exact = page.locator('.calendar-day').filter({ has: page.getByRole('button', { name: 'Show sessions for 2026-09-03', exact: true }) })
    await expect(exact.locator('.calendar-event')).toHaveCount(5)
    await expect(exact.locator('.calendar-more')).toHaveCount(0)
    const empty = page.locator('.calendar-day').filter({ has: page.getByRole('button', { name: 'Show sessions for 2026-09-04', exact: true }) })
    await expect(empty.locator('.calendar-event, .calendar-more')).toHaveCount(0)
    const more = busy.getByRole('button', { name: 'Show 3 more sessions for 2026-09-02' })
    await expect(more).toBeVisible()
    await expect(more).toHaveText('+3 more')
    if (mode === 'Monthly' && page.viewportSize().width <= 780) {
      await expect(busy.locator('.calendar-day-events')).toBeHidden()
    } else {
      expect((await more.boundingBox()).y).toBeGreaterThan((await busy.locator('.calendar-event').last().boundingBox()).y)
    }
    await more.click()
    const dialog = page.getByRole('dialog', { name: 'Calendar sessions' })
    await expect(dialog.locator('.calendar-event')).toHaveCount(8)
    await expect(dialog.locator('.calendar-event').last()).toContainText('15:00–16:00')
    await page.getByRole('button', { name: 'Close calendar sessions' }).click()
    await expect(dialog).toHaveCount(0)
  }
  await page.getByRole('button', { name: 'Show 3 more sessions for 2026-09-02' }).click()
  await page.getByRole('dialog', { name: 'Calendar sessions' }).locator('.calendar-event').last().click()
  await expect(page).toHaveURL(/#\/sessions\/busy-7$/)
  await expect(page.getByRole('button', { name: 'Client Signature', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Monthly', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('Calendar date')).toHaveValue('2026-09-02')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0)
})

test('M4 calendar date popup closes with browser Back and reopens an empty day without restoring a daily dashboard', async ({ page }) => {
  await page.goto('/#/dashboard')
  await page.getByRole('button', { name: 'Monthly', exact: true }).click()
  await page.getByLabel('Calendar date').fill('2032-02-29')
  await page.getByRole('button', { name: 'Show sessions for 2032-02-29', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Calendar sessions' })).toContainText('No sessions for this day.')
  await page.goBack()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Calendar date')).toHaveValue('2032-02-29')
  await page.goForward()
  await expect(page.getByRole('dialog', { name: 'Calendar sessions' })).toBeVisible()
  await page.getByRole('button', { name: 'Close calendar sessions' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Selected day sessions')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Today', exact: true })).toHaveCount(0)
})
