import { expect, test, selectDemoIdentity, expandSidebarSection } from './fixtures.js'

test('M4 owner profile uses stored account details and preserves native Back', async ({ page }) => {
  await page.goto('/#/clients')
  await expect(page.getByRole('heading', { name: 'Clients', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  await page.getByRole('menuitem', { name: 'My Profile', exact: true }).click()
  await expect(page).toHaveURL(/#\/owner-profile$/)
  await expect(page.getByRole('heading', { name: 'Chau', exact: true })).toBeVisible()
  await expect(page.getByLabel('Account status')).toHaveText('Active')
  const account = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Account Details' }) })
  await expect(account).toContainText('Owner / Site Admin')
  await expect(account.getByRole('button')).toHaveCount(0)
  await expect(page.getByText('Next migration slice')).toHaveCount(0)
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  expect(overflow).toBe(false)
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Clients', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Account Details' })).toBeVisible()
})

test('M4 content is available, unknown routes are explicit and owner profile is scoped', async ({ page }) => {
  await page.goto('/#/content')
  await expect(page.getByRole('heading', { name: 'Content Management', exact: true })).toBeVisible()
  await expandSidebarSection(page, 'Content Management')
  await expect(page.locator('.sidebar').getByRole('button', { name: 'Content Management', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Add Content', exact: true })).toBeVisible()
  await page.evaluate(() => { location.hash = '#/unknown-page' })
  await expect(page.getByRole('heading', { name: 'Page unavailable', exact: true })).toBeVisible()
  await selectDemoIdentity(page, 'u-marcus')
  await expect(page.getByRole('heading', { name: 'Trainer Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { location.hash = '#/owner-profile' })
  await expect(page.getByText('This profile is available to the owner.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Account Details' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Open profile menu' }).click()
  await page.getByRole('menuitem', { name: 'My Profile', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Marcus Tan', exact: true })).toBeVisible()
})
