import { webcrypto } from 'node:crypto'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import App from './App.jsx'
import { ActionConfirmationProvider } from './components/ActionConfirmationProvider.jsx'
import { EditGuardProvider } from './components/EditGuardProvider.jsx'
import { NotificationProvider } from './components/NotificationProvider.jsx'
import { mockDb } from './services/mockDb.js'
import { MOCK_SESSION_KEY } from './services/authService.js'
import { mockAccountPassword } from './data/mockPolicy.js'
import { drawSignature } from './test/drawSignature.js'
import { portalServices } from './services/defaultPortalServices.js'
import { withBusyCalendar } from './test/fixtures/calendar.js'
import * as progressPdf from './features/clients/progressReportPdf.jsx'

function profileTab(name) {
  const menu = document.querySelector('details.profile-menu')
  menu?.setAttribute('open', '')
  fireEvent.click(within(menu).getByRole('button', { name, exact: true }))
}

it('restores client history tab and page through a session, Back, Forward and a data refresh', async () => {
  mockDb.mutate(db => {
    const source = db.sessions.find(item => item.id === 's0')
    db.sessions = Array.from({ length: 22 }, (_, index) => ({ ...source, id: `history-${index}`, clientId: 'c1', status: 'completed', date: '2026-08-01', sessionNumber: index + 1 }))
  })
  show('clients/c1')
  await screen.findByRole('heading', { name: 'Amanda Lim' })
  profileTab('Session History')
  click('Next')
  const list = screen.getByLabelText('Session History')
  const first = list.firstElementChild.textContent
  fireEvent.click(within(list).getAllByRole('button', { name: 'View' })[0])
  await screen.findByRole('heading', { name: 'Session Overview' })
  click('Back')
  await screen.findByRole('heading', { name: 'Session History' })
  expect(screen.getByLabelText('List pages')).toHaveTextContent('Page 2 of 3')
  expect(screen.getByLabelText('Session History').firstElementChild).toHaveTextContent(first)
  await act(async () => { window.dispatchEvent(new Event('focus')) })
  await waitFor(() => expect(screen.getByRole('heading', { name: 'Session History' })).toBeVisible())
  await act(async () => { history.forward() })
  await screen.findByRole('heading', { name: 'Session Overview' })
  await act(async () => { history.back() })
  await screen.findByRole('heading', { name: 'Session History' })
  expect(screen.getByLabelText('List pages')).toHaveTextContent('Page 2 of 3')
})

it('restores nested trainer assigned-client filters after returning from a client profile', async () => {
  mockDb.mutate(db => {
    const source = db.clients[0]
    db.clients.push(...Array.from({ length: 12 }, (_, index) => ({ ...structuredClone(source), id: `assigned-${index}`, name: `Assigned ${index}`, email: `assigned-${index}@example.com` })))
  })
  show('trainers/t1')
  await screen.findByRole('heading', { name: 'Marcus Tan' })
  profileTab('Assigned Clients')
  const assigned = screen.getByLabelText('Assigned client list')
  expect(assigned.querySelectorAll('.quick-row')).toHaveLength(10)
  click('Next')
  expect(assigned.querySelectorAll('.quick-row')).toHaveLength(3)
  fireEvent.click(within(assigned).getAllByRole('button', { name: 'View' })[0])
  await screen.findByRole('heading', { name: 'General Information' })
  click('Back')
  await screen.findByRole('heading', { name: 'Assigned Clients' })
  expect(screen.getByLabelText('List pages')).toHaveTextContent('Page 2 of 2')
  change('Search assigned clients', 'Amanda')
  fireEvent.click(within(screen.getByLabelText('Assigned client list')).getByRole('button', { name: 'View' }))
  await screen.findByRole('heading', { name: 'Amanda Lim' })
  profileTab('Progress')
  click('Back')
  await screen.findByRole('heading', { name: 'Assigned Clients' })
  expect(screen.getByLabelText('Search assigned clients')).toHaveValue('Amanda')
  expect(screen.getByLabelText('Assigned client list')).toHaveTextContent('Amanda Lim')
})

it('restores list filters after detail navigation and isolates view state when switching account', async () => {
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(new Date('2026-09-02T04:00:00Z'))
  mockDb.mutate(db => {
    const future = db.sessions.find(session => session.id === 's2')
    db.sessions = [
      ...db.sessions.filter(session => ['s0', 's1', 's2'].includes(session.id)),
      { ...future, id: 'later-time', from: '20:00', to: '21:00' },
      { ...future, id: 'other-trainer', trainerId: 't2', date: '2026-09-08' },
    ]
  })
  show('sessions')
  await screen.findByRole('heading', { name: 'Sessions', exact: true })
  expect(screen.getByLabelText('Filter sessions by period')).toHaveValue('upcoming')
  let rows = screen.getByLabelText('Session list').querySelectorAll('article')
  expect(rows).toHaveLength(4)
  expect(rows[0]).toHaveTextContent('02 Sept 2026')
  expect(screen.getByLabelText('Session list')).not.toHaveTextContent('31 Aug 2026')
  change('Filter sessions by period', 'all')
  change('Search sessions', 'Amanda')
  rows = screen.getByLabelText('Session list').querySelectorAll('article')
  expect(rows).toHaveLength(5)
  expect(rows[0]).toHaveTextContent('08 Sept 2026')
  expect(rows[1]).toHaveTextContent('20:00–21:00')
  expect(rows[2]).toHaveTextContent('18:00–19:00')
  expect(rows[4]).toHaveTextContent('31 Aug 2026')
  fireEvent.click(within(rows[0]).getByRole('button', { name: /View session/ }))
  await screen.findByRole('heading', { name: 'Session Overview' })
  click('Back')
  await screen.findByRole('heading', { name: 'Sessions', exact: true })
  expect(screen.getByLabelText('Filter sessions by period')).toHaveValue('all')
  expect(screen.getByLabelText('Search sessions')).toHaveValue('Amanda')
  expect(screen.getByLabelText('Session list').querySelector('article')).toHaveTextContent('08 Sept 2026')
  click('Clients')
  await screen.findByRole('heading', { name: 'Clients' })
  change('Search client', 'Amanda')
  change('Filter clients by type', 'Individual')
  click('View Amanda Lim')
  await screen.findByRole('heading', { name: 'Amanda Lim' })
  click('Back')
  await screen.findByRole('heading', { name: 'Clients' })
  expect(screen.getByLabelText('Search client')).toHaveValue('Amanda')
  expect(screen.getByLabelText('Filter clients by type')).toHaveValue('Individual')
  change('Demo identity', 'u-marcus')
  await screen.findByRole('heading', { name: 'Trainer Dashboard' })
  click('Trainer section'); click('Clients')
  await screen.findByRole('heading', { name: 'Clients' })
  expect(screen.queryByLabelText('Filter clients by trainer')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Search client')).toHaveValue('')
  expect(screen.getByLabelText('Filter clients by type')).toHaveValue('')
  click('Sessions')
  await screen.findByRole('heading', { name: 'Sessions', exact: true })
  expect(screen.getByLabelText('Filter sessions by period')).toHaveValue('upcoming')
  expect(screen.getByLabelText('Search sessions')).toHaveValue('')
  expect(screen.getByLabelText('Session list').querySelectorAll('article')).toHaveLength(3)
  change('Filter sessions by period', 'all')
  rows = screen.getByLabelText('Session list').querySelectorAll('article')
  expect(rows).toHaveLength(4)
  expect(rows[0]).toHaveTextContent('07 Sept 2026')
  expect(rows[0]).toHaveTextContent('20:00–21:00')
  expect(rows[3]).toHaveTextContent('31 Aug 2026')
  change('Filter sessions by period', 'history')
  expect(screen.getByLabelText('Session list').querySelectorAll('article')).toHaveLength(1)
  expect(screen.getByLabelText('Session list')).toHaveTextContent('31 Aug 2026')
})

function show(path='dashboard',signedIn=true,services) {
  if(signedIn) localStorage.setItem(MOCK_SESSION_KEY,JSON.stringify({userId:'u-owner',expiresAt:Date.now()+3600000}))
  window.history.replaceState(null,'',`/#/${path}`)
  return render(<NotificationProvider><ActionConfirmationProvider><EditGuardProvider><App services={services}/></EditGuardProvider></ActionConfirmationProvider></NotificationProvider>)
}
const change=(name,value)=>fireEvent.change(screen.getByLabelText(name),{target:{value}})
const click=name=>fireEvent.click(screen.getByRole('button',{name,exact:true}))
// Query the explicit button labels/mode group without computing accessible names
// for every calendar session. Native button and label checks remain.
const calendarDate = day => screen.getByLabelText(`Show sessions for ${day}`, { selector: 'button', exact: true })
const calendarDay = day => document.querySelector(`.calendar-day[data-date="${day}"]`)
const displayedCalendarDates = () => [...document.querySelectorAll('.calendar-day')].map(day => day.dataset.date)
const calendarMode = name => within(screen.getByLabelText('Calendar view')).getByRole('button', { name, exact: true })
const closeCalendar = () => fireEvent.click(screen.getByLabelText('Close calendar sessions', { selector: 'button', exact: true }))
const septemberDates = Array.from({ length: 30 }, (_, index) => `2026-09-${String(index + 1).padStart(2, '0')}`)
function fixCalendarClock() {
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(new Date('2026-09-02T04:00:00Z'))
}
beforeEach(()=>{localStorage.clear();mockDb.reset();mockDb.mutate(db => { db.sessions.find(item => item.id === 's1').date = '2026-09-02'; db.sessions.find(item => item.id === 's2').date = '2026-09-07' });vi.stubGlobal('crypto',webcrypto);window.scrollTo=vi.fn();vi.stubGlobal('matchMedia', query => ({ matches: query === '(min-width: 700px)', addEventListener() {}, removeEventListener() {} }))})
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})

it('blocks account actions until a delayed switch commits and restores the current account after failure', async () => {
  let release
  const switchDemoIdentity = vi.fn().mockRejectedValueOnce(new Error('Account unavailable')).mockImplementation(async id => {
    await new Promise(resolve => { release = resolve })
    return portalServices.auth.switchDemoIdentity(id)
  })
  show('dashboard', true, { ...portalServices, auth: { ...portalServices.auth, switchDemoIdentity } })
  await screen.findByRole('heading', { name: 'Calendar' })
  change('Demo identity', 'u-marcus')
  await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('Account unavailable'))
  expect(document.querySelector('.portal-shell')).toHaveAttribute('data-user-id', 'u-owner')
  expect(document.querySelector('.sidebar')).not.toHaveAttribute('inert')
  change('Demo identity', 'u-marcus')
  await screen.findByText('Switching account…')
  expect(document.querySelector('.sidebar')).toHaveAttribute('inert')
  expect(document.querySelector('.portal-main')).toHaveAttribute('inert')
  expect(document.querySelector('.portal-shell')).toHaveAttribute('data-user-id', 'u-owner')
  // Even a duplicate programmatic event cannot start another pending switch.
  change('Demo identity', 'u-daniel')
  expect(switchDemoIdentity).toHaveBeenCalledTimes(2)
  await act(async () => { release() })
  await waitFor(() => expect(document.querySelector('.portal-shell')).toHaveAttribute('data-user-id', 'u-marcus'))
  expect(document.querySelector('.portal-shell')).toHaveAttribute('aria-busy', 'false')
  expect(document.querySelector('.sidebar')).not.toHaveAttribute('inert')
  expect(screen.queryByText('Switching account…')).not.toBeInTheDocument()
})

it('M4 assembled app signs in, exposes a real calendar and signs out to an account form',async()=>{
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(new Date('2026-09-02T04:00:00Z'))
  show('dashboard',false)
  await screen.findByRole('heading',{name:'Sign in'})
  change('Account','u-owner');change('Password',mockAccountPassword);click('Sign In')
  await screen.findByRole('heading',{name:'Calendar'})
  expect(calendarMode('Weekly')).toHaveAttribute('aria-pressed', 'true')
  expect(screen.queryByLabelText('Calendar date')).not.toBeInTheDocument()
  const initialWeek = ['2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08']
  expect(displayedCalendarDates()).toEqual(initialWeek)
  click('Next calendar period')
  expect(displayedCalendarDates()).toEqual(['2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12', '2026-09-13', '2026-09-14', '2026-09-15'])
  click('Previous calendar period')
  expect(displayedCalendarDates()).toEqual(initialWeek)
  click('Monthly');expect(screen.getByRole('button',{name:'Monthly'})).toHaveAttribute('aria-pressed','true')
  expect(screen.queryByLabelText('Calendar date')).not.toBeInTheDocument()
  expect(displayedCalendarDates()).toEqual(septemberDates)
  click('Next calendar period')
  expect(displayedCalendarDates()).toEqual(Array.from({ length: 31 }, (_, index) => `2026-10-${String(index + 1).padStart(2, '0')}`))
  expect(document.querySelector('.calendar-range option:checked')).toHaveTextContent('Oct 2026')
  click('Next calendar period')
  expect(displayedCalendarDates()).toEqual(Array.from({ length: 30 }, (_, index) => `2026-11-${String(index + 1).padStart(2, '0')}`))
  expect(screen.queryByLabelText('Selected day sessions')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Today', exact: true })).not.toBeInTheDocument()
  expect(screen.getByLabelText('Monthly calendar').querySelectorAll('.calendar-event')).toHaveLength(0)
  click('Next calendar period')
  expect(displayedCalendarDates()).toEqual(Array.from({ length: 31 }, (_, index) => `2026-12-${String(index + 1).padStart(2, '0')}`))
  expect(screen.getByLabelText('Monthly calendar').querySelectorAll('button, .calendar-count-label, .calendar-date-action')).toHaveLength(0)
  click('Previous calendar period')
  expect(calendarDay('2026-11-30').querySelector('time')).toHaveTextContent('30')
  click('Previous calendar period')
  expect(displayedCalendarDates()).toEqual(Array.from({ length: 31 }, (_, index) => `2026-10-${String(index + 1).padStart(2, '0')}`))
  click('Previous calendar period')
  expect(displayedCalendarDates()).toEqual(septemberDates)
  click('Open profile menu');fireEvent.click(screen.getByRole('menuitem',{name:'Sign Out'}))
  await screen.findByRole('heading',{name:'Sign in'})
  expect(screen.queryByRole('heading',{name:'Calendar'})).not.toBeInTheDocument()
})
it('M4 assembled content form previews safe text, saves and reopens persisted content',async()=>{
  show('content/new');await screen.findByLabelText('Content title')
  change('Content title','New studio details');change('Content key','studio/details');change('Content body','<script>unsafe()</script> Our studio.');change('Content status','ready')
  click('Preview');expect(screen.getByRole('dialog',{name:'Content preview'})).toHaveTextContent('<script>unsafe()</script>')
  expect(document.querySelector('.content-preview script')).toBeNull();click('Close Preview')
  click('Save Content');fireEvent.click(within(screen.getByRole('dialog',{name:'Save content?'})).getByRole('button',{name:'Save Content'}))
  await waitFor(()=>expect(mockDb.read().contentEntries).toHaveLength(1))
  await waitFor(()=>expect(window.location.hash).toMatch(/#\/content\/content-/))
  expect(mockDb.read().contentEntries[0]).toMatchObject({key:'studio/details',status:'ready'})
})
it('M4 assembled signature dialog requires drawing, supports clear and saves visible evidence',async()=>{
  const acknowledge = vi.spyOn(portalServices.sessionService, 'acknowledge')
  show('sessions/s1');fireEvent.click(await screen.findByRole('button',{name:'Client Signature'}))
  const signing = within(screen.getByRole('dialog', { name: 'Client signature', exact: true }))
  const reviewCompletion = signing.getByRole('button', { name: 'Review Completion', exact: true })
  expect(reviewCompletion).toBeDisabled()
  drawSignature(signing.getByRole('img',{name:'Draw client signature'}));expect(reviewCompletion).toBeEnabled()
  fireEvent.click(signing.getByRole('button', { name: 'Clear Signature', exact: true }));expect(reviewCompletion).toBeDisabled()
  drawSignature(signing.getByRole('img',{name:'Draw client signature'}));fireEvent.click(reviewCompletion)
  const dialog=screen.getByRole('dialog',{name:'Complete this session?'})
  expect(within(dialog).getByRole('img')).toBeInTheDocument()
  fireEvent.click(within(dialog).getByRole('button',{name:'Complete Session'}))
  await waitFor(() => expect(acknowledge).toHaveBeenCalledTimes(1))
  await act(async () => { await acknowledge.mock.results[0].value })
  fireEvent.click(await screen.findByRole('button',{name:'View Client Signature'}))
  const preview = screen.getByRole('dialog',{name:'Client signature'})
  expect(preview).toHaveTextContent('Amanda Lim')
  expect(preview).toHaveTextContent('Signed on')
  const saved = mockDb.read().sessions.find(item => item.id === 's1')
  expect(preview.querySelector('time')).toHaveAttribute('datetime', saved.acknowledgement.recordedAt)
  expect(saved.acknowledgementHistory).toEqual([saved.acknowledgement])
  expect(saved.acknowledgement.recordedBy).toMatchObject({ id: 'u-owner', role: 'owner' })
  expect(within(preview).queryByRole('button', { name: 'Clear Signature' })).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Update Completion' })).not.toBeInTheDocument()
  expect(mockDb.read().packageCreditTransactions.filter(item=>item.sessionId==='s1')).toHaveLength(1)
})
it('M4 assembled app retries loads and uses an injected account for saves, refresh and sign-out without demo controls',async()=>{
  const owner = { id: 'external-id', name: 'External account', role: 'owner' }
  const data = { users: [owner], clients: [], trainers: [], sessions: [], messages: [], packages: [], exerciseLibrary: [], contentEntries: [], remunerationViews: [] }
  const snapshot = { user: null, accounts: [owner], capabilities: { demoControls: false }, policy: { timeZone: 'UTC' }, data: null }
  const services = {
    load: vi.fn().mockRejectedValueOnce(new Error('Network unavailable')).mockImplementation(async () => structuredClone(snapshot)),
    auth: {
      signIn: vi.fn(async () => { snapshot.user = owner; snapshot.data = data; return owner }),
      signOut: vi.fn(async () => { snapshot.user = null; snapshot.data = null }),
    },
    contentService: {
      save: vi.fn().mockRejectedValueOnce(new Error('Save unavailable')).mockImplementation(async ({ draft }) => {
        const saved = { ...draft, id: 'external-content', version: 1 }
        data.contentEntries = [saved]
        return saved
      }),
    },
  }
  const localRecords = mockDb.read()
  show('content/new',false,services)
  await screen.findByRole('heading',{name:'Unable to load the portal'});click('Retry')
  await screen.findByRole('heading',{name:'Sign in'})
  expect(screen.getByRole('option',{name:'External account'})).toHaveValue('external-id')
  expect(screen.queryByText(mockAccountPassword)).not.toBeInTheDocument()
  change('Account', owner.id); change('Password', 'external-password'); click('Sign In')
  await screen.findByLabelText('Content title')
  expect(services.auth.signIn).toHaveBeenCalledWith({ identifier: owner.id, password: 'external-password' })
  expect(document.querySelector('.portal-shell')).toHaveAttribute('data-user-id', owner.id)
  expect(screen.queryByLabelText('Demo identity')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Reset Demo Data' })).not.toBeInTheDocument()

  change('Content title', 'External studio'); change('Content key', 'external/studio'); change('Content body', 'Saved through the injected service.')
  const confirmSave = () => {
    click('Save Content')
    fireEvent.click(within(screen.getByRole('dialog', { name: 'Save content?' })).getByRole('button', { name: 'Save Content' }))
  }
  confirmSave()
  await waitFor(() => expect(screen.getAllByRole('alert').some(item => item.textContent.includes('Save unavailable'))).toBe(true))
  expect(screen.getByLabelText('Content title')).toHaveValue('External studio')
  expect(data.contentEntries).toEqual([])
  const loadsBeforeSave = services.load.mock.calls.length
  confirmSave()
  await waitFor(() => expect(window.location.hash).toBe('#/content/external-content'))
  await waitFor(() => expect(screen.getByLabelText('Content title')).toHaveValue('External studio'))
  expect(services.contentService.save).toHaveBeenCalledTimes(2)
  expect(services.contentService.save).toHaveBeenLastCalledWith({ id: undefined, expectedVersion: undefined, draft: { title: 'External studio', key: 'external/studio', body: 'Saved through the injected service.', status: 'draft' } }, owner)
  expect(services.load.mock.calls.length).toBeGreaterThan(loadsBeforeSave)

  services.load.mockRejectedValueOnce(new Error('Refresh unavailable'))
  click('Open profile menu'); fireEvent.click(screen.getByRole('menuitem', { name: 'Sign Out' }))
  await screen.findByRole('heading', { name: 'Sign in' })
  expect(services.auth.signOut).toHaveBeenCalledOnce()
  expect(document.querySelector('.portal-shell')).toBeNull()
  expect(screen.queryByLabelText('Content title')).not.toBeInTheDocument()
  expect(mockDb.read()).toEqual(localRecords)
  expect(localStorage.getItem(MOCK_SESSION_KEY)).toBeNull()
})
it('M4 assembled password form keeps a failed draft and saves a verified replacement',async()=>{
  show('change-password');await screen.findByLabelText('Current password')
  change('Current password','wrong-password');change('New password','ReplacementPass42!');change('Confirm new password','ReplacementPass42!');click('Save Password')
  fireEvent.click(within(screen.getByRole('dialog',{name:'Change password?'})).getByRole('button',{name:'Change Password'}))
  await waitFor(()=>expect(screen.getAllByRole('alert').some(item=>item.textContent.includes('current password is incorrect'))).toBe(true))
  expect(screen.getByLabelText('New password')).toHaveValue('ReplacementPass42!')
  change('Current password',mockAccountPassword);click('Save Password')
  fireEvent.click(within(screen.getByRole('dialog',{name:'Change password?'})).getByRole('button',{name:'Change Password'}))
  await waitFor(()=>expect(screen.getByLabelText('New password')).toHaveValue(''))
  expect(localStorage.getItem('fitfinity-demo-credentials-v1')).not.toContain('ReplacementPass42!')
})

it('resets the route on sign-out before unmounting and returns to Dashboard after password replacement and re-login', async () => {
  show('change-password')
  await screen.findByLabelText('Current password')
  change('Current password', mockAccountPassword)
  change('New password', 'NewDemoPassword42!')
  change('Confirm new password', 'NewDemoPassword42!')
  click('Save Password')
  fireEvent.click(within(screen.getByRole('dialog', { name: 'Change password?' })).getByRole('button', { name: 'Change Password' }))
  await waitFor(() => expect(screen.getByLabelText('Current password')).toHaveValue(''))
  click('Open profile menu'); fireEvent.click(screen.getByRole('menuitem', { name: 'Sign Out' }))
  await screen.findByRole('heading', { name: 'Sign in' })
  expect(location.hash).toBe('#/dashboard')
  expect(document.querySelector('.portal-shell')).toBeNull()
  change('Account', 'u-owner'); change('Password', mockAccountPassword); click('Sign In')
  await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('incorrect'))
  change('Password', 'NewDemoPassword42!'); click('Sign In')
  await screen.findByRole('heading', { name: 'Calendar' })
  expect(location.hash).toBe('#/dashboard')
  expect(screen.queryByLabelText('Current password')).not.toBeInTheDocument()
})

it('password notifications reflect loaded requirements and block invalid drafts before saving', async () => {
  mockDb.mutate(db => { db.settings.password = { minimumLength: 16, maximumLength: 20 } })
  const changePassword = vi.fn()
  show('change-password', true, { ...portalServices, auth: { ...portalServices.auth, changePassword } })
  await screen.findByLabelText('New password')
  expect(document.querySelector('.account-form .helper')).toBeNull()
  fireEvent.focus(screen.getByLabelText('New password'))
  expect(screen.getByRole('status')).toHaveTextContent('16–20 characters')
  click('Dismiss notification'); click('Password requirements')
  expect(screen.getByRole('status')).toHaveTextContent('differ from your current password and match the confirmation')
  click('Save Password')
  expect(screen.getByRole('alert')).toHaveTextContent('Enter your current password.')
  change('Current password', mockAccountPassword)
  for (const draft of ['x'.repeat(15), 'x'.repeat(21)]) {
    change('New password', draft); change('Confirm new password', draft); click('Save Password')
    expect(screen.getByRole('alert')).toHaveTextContent('16–20 characters')
    expect(screen.getByLabelText('New password')).toHaveValue(draft)
  }
  change('New password', 'x'.repeat(16)); change('Confirm new password', 'y'.repeat(16)); click('Save Password')
  expect(screen.getByRole('alert')).toHaveTextContent('The new passwords do not match.')
  change('Current password', 'x'.repeat(16)); change('Confirm new password', 'x'.repeat(16)); click('Save Password')
  expect(screen.getByRole('alert')).toHaveTextContent('Choose a different new password.')
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  expect(changePassword).not.toHaveBeenCalled()
})

it('dashboard renewals share persisted read state with the routed renewal filter', async () => {
  show(); await screen.findByRole('heading', { name: 'Calendar' })
  const renewals = screen.getByLabelText('Renewal messages')
  expect(renewals.querySelectorAll('.message-title-row')).toHaveLength(1)
  expect(renewals.querySelector('.message-title-row')).toHaveTextContent('Renewal follow-up: Nadia Koh')
  expect(renewals.compareDocumentPosition(screen.getByLabelText('Weekly calendar')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  fireEvent.click(within(renewals).getByRole('button', { name: 'Open Renewal follow-up: Nadia Koh' }))
  expect(await screen.findByRole('dialog', { name: 'Renewal follow-up: Nadia Koh' })).toHaveTextContent('10/12 sessions used · 2 sessions remaining.')
  expect(mockDb.read().messages.find(item => item.id === 'm3').read).toBe(true)
  click('Close message')
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  click('View All Renewals')
  expect(window.location.hash).toBe('#/messages/renewals')
  expect(within(screen.getByRole('group', { name: 'Message categories' })).getByRole('button', { name: 'Renewals', exact: true })).toHaveAttribute('aria-current', 'true')
  expect(screen.getByRole('button', { name: 'Read Renewal follow-up: Nadia Koh' })).toBeVisible()
})

it('calendar dates open scoped sessions in a routed dialog and session Back retains the calendar', async () => {
  fixCalendarClock()
  show(); await screen.findByRole('heading', { name: 'Calendar' })
  fireEvent.click(calendarMode('Monthly'))
  fireEvent.click(calendarDate('2026-09-02'))
  const dialog = await screen.findByRole('dialog', { name: 'Calendar sessions' })
  expect(window.location.hash).toBe('#/dashboard/day/2026-09-02')
  expect(document.body.style.position).toBe('fixed')
  const session = within(dialog).getAllByRole('button').find(button => button.textContent.includes('Amanda Lim'))
  expect(session).toBeDefined(); fireEvent.click(session)
  await screen.findByRole('button', { name: 'Client Signature' })
  click('Back')
  await screen.findByRole('heading', { name: 'Calendar' })
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  expect(calendarMode('Monthly')).toHaveAttribute('aria-pressed', 'true')
  expect(displayedCalendarDates()).toEqual(septemberDates)
  expect(document.querySelector('.calendar-range option:checked')).toHaveTextContent('Sept 2026')
})

it('calendar empty-day dialog closes with Escape and a trainer sees only their sessions', async () => {
  fixCalendarClock()
  show(); await screen.findByRole('heading', { name: 'Calendar' })
  change('Demo identity', 'u-marcus')
  await screen.findByRole('heading', { name: 'Trainer Dashboard' })
  fireEvent.click(calendarDate('2026-09-02'))
  const ownSessions = mockDb.read().sessions.filter(item => item.date === '2026-09-02' && item.trainerId === 't1')
  const dialog = screen.getByRole('dialog', { name: 'Calendar sessions' })
  expect(dialog.querySelectorAll('.calendar-event')).toHaveLength(ownSessions.length)
  closeCalendar()
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  await act(async () => { window.location.hash = '#/dashboard/day/2032-02-29' })
  expect(await screen.findByRole('dialog', { name: 'Calendar sessions' })).toHaveTextContent('No sessions for this day.')
  fireEvent.keyDown(screen.getByLabelText('Close calendar sessions', { selector: 'button', exact: true }), { key: 'Escape' })
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(document.body.style.position).not.toBe('fixed')
})

it('owner counts and trainer weekly rows open complete scoped days and retain Monthly state on Back', async () => {
  fixCalendarClock()
  mockDb.write(withBusyCalendar(mockDb.read()))
  show(); await screen.findByRole('heading', { name: 'Calendar' })
  expect(calendarDate('2026-09-02').querySelector('strong')).toHaveTextContent(/^14$/)
  expect(screen.getByLabelText('Weekly calendar').querySelector('.calendar-event')).toBeNull()
  fireEvent.click(calendarDate('2026-09-02'))
  expect(screen.getByRole('dialog').querySelectorAll('.calendar-trainer-group')).toHaveLength(2)
  expect(screen.getByRole('dialog').querySelectorAll('.calendar-event')).toHaveLength(14)
  closeCalendar()
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  change('Demo identity', 'u-marcus')
  await screen.findByRole('heading', { name: 'Trainer Dashboard' })
  for (const mode of ['Weekly', 'Monthly']) {
    fireEvent.click(calendarMode(mode))
    expect(screen.queryByLabelText('Calendar date')).not.toBeInTheDocument()
    const date = calendarDate('2026-09-02')
    expect(date).toHaveAttribute('aria-haspopup', 'dialog')
    const busy = date.closest('.calendar-day')
    if (mode === 'Weekly') expect(busy.querySelectorAll('.calendar-event')).toHaveLength(8)
    else {
      expect(date.querySelector('strong')).toHaveTextContent(/^8$/)
      expect(busy.querySelector('.calendar-event')).toBeNull()
    }
    const empty = calendarDay('2026-09-04')
    expect(empty.querySelector('.calendar-event, .calendar-more')).toBeNull()
    expect(empty.querySelector('button, [tabindex], .calendar-date-action, .calendar-count-label')).toBeNull()
    expect(empty).not.toHaveTextContent('View day')
    if (mode === 'Weekly') {
      expect(empty.querySelector('.calendar-agenda-date')).toHaveTextContent('Friday, 04 Sept 2026')
      expect(empty).toHaveTextContent('No sessions')
    } else {
      expect(empty.querySelector('time')).toHaveTextContent('4')
      expect(empty).not.toHaveTextContent('No sessions')
    }
    fireEvent.click(date)
    const dialog = screen.getByRole('dialog', { name: 'Calendar sessions' })
    expect(dialog.querySelectorAll('.calendar-event')).toHaveLength(8)
    expect(dialog.querySelector('.calendar-event:last-child strong')).toHaveTextContent('15:00–16:00')
    closeCalendar()
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  }
  fireEvent.click(calendarDate('2026-09-02'))
  fireEvent.click(screen.getByRole('dialog', { name: 'Calendar sessions' }).querySelector('.calendar-event:last-child'))
  await screen.findByRole('button', { name: 'Client Signature' })
  expect(window.location.hash).toBe('#/sessions/busy-7')
  click('Back'); await screen.findByRole('heading', { name: 'Calendar' })
  expect(calendarMode('Monthly')).toHaveAttribute('aria-pressed', 'true')
  expect(displayedCalendarDates()).toEqual(septemberDates)
  expect(document.querySelector('.calendar-range option:checked')).toHaveTextContent('Sept 2026')
})


it('replaces renewal controls with owner-only progress report activity that survives refresh', async () => {
  vi.spyOn(progressPdf, 'progressReportPdf').mockResolvedValue(new Blob(['%PDF-1.4'], { type: 'application/pdf' }))
  const create = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:report')
  vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
  vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
  show('clients/c1')
  await screen.findByRole('heading', { name: 'General Information' })
  expect(screen.queryByText('Renewal status')).not.toBeInTheDocument()
  expect(screen.queryByText('Renewal History')).not.toBeInTheDocument()
  profileTab('Progress')
  fireEvent.click(within(screen.getByLabelText('Progress packages')).getAllByRole('button', { name: 'View' })[0])
  click('View Export/WhatsApp History')
  await screen.findByText('No export or WhatsApp history yet.')
  click('Export Progress Report')
  await waitFor(() => expect(document.querySelector('.report-history-row')).toHaveTextContent('PDF export'))
  expect(create).toHaveBeenCalledTimes(1)
  const saved = mockDb.read().progressReportEvents[0]
  expect(saved.by.id).toBe('u-owner')
  expect(document.querySelector(`time[datetime="${saved.at}"]`)).toBeVisible()
  await act(async () => { window.dispatchEvent(new Event('focus')) })
  await waitFor(() => expect(document.querySelector('.report-history-row')).toHaveTextContent('PDF export'))
  change('Demo identity', 'u-marcus')
  await screen.findByRole('heading', { name: 'Trainer Dashboard' })
  await act(async () => { location.hash = '#/clients/c1' })
  await screen.findByRole('heading', { name: 'General Information' })
  profileTab('Progress')
  expect(screen.queryByRole('button', { name: 'View Export/WhatsApp History' })).not.toBeInTheDocument()
})

it('opens a package report through shared navigation and restores its package list page with Back and Forward', async () => {
  mockDb.mutate(db => {
    const client = db.clients[0]
    client.packageHistory = Array.from({ length: 12 }, (_, index) => ({ id: `purchase-${index}`, total: 12, used: 12,
      startDate: `20${10 + index}-01-01`, endDate: `20${10 + index}-04-01` }))
  })
  show('clients/c1')
  await screen.findByRole('heading', { name: 'Amanda Lim' })
  profileTab('Progress')
  const list = screen.getByLabelText('Progress packages')
  expect(list.querySelectorAll('article')).toHaveLength(10)
  click('Next')
  const selected = list.querySelector('article')
  const id = selected.dataset.packageId
  fireEvent.click(within(selected).getByRole('button', { name: 'View' }))
  await screen.findByText('No completed exercise loads yet.')
  expect(location.hash).toBe(`#/clients/c1/progress/${id}`)
  click('Back')
  await screen.findByRole('heading', { name: 'Progress Packages' })
  expect(screen.getByLabelText('List pages')).toHaveTextContent('Page 2 of 2')
  expect(screen.getByLabelText('Progress packages').querySelector('article').dataset.packageId).toBe(id)
  await act(async () => { history.forward() })
  await screen.findByText('No completed exercise loads yet.')
  expect(location.hash).toBe(`#/clients/c1/progress/${id}`)
  profileTab('Upcoming Sessions')
  expect(screen.getByRole('heading', { name: 'Upcoming Sessions' })).toBeVisible()
  expect(location.hash).toBe('#/clients/c1')
})
